fix: bug fix about lock
awslabs/stable-diffusion-aws-extension pull request #110
Opened 2023-07-27 06:56 UTC by o0OooO

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-07-27 09:23 UTC, NingLu approved these changes

2023-07-27 09:47 UTC, AoyuQC commented on scripts/api.py
Please choose one of two methods to print information in api.py. print or logger

2023-07-27 09:48 UTC, AoyuQC requested changes
Please improve log method in api.py.

2023-07-28 02:52 UTC, AoyuQC approved these changes

2023-07-28 02:52 UTC, merged