feat: initial new inference data flow from python part (part 1)
awslabs/stable-diffusion-aws-extension pull request #113
Opened 2023-07-31 15:52 UTC by alvindaiyan

## Description

- new apis for txt2img and img2img
- refactored infra part code
- new ui feature for capture data from python instead of js when txt2img and img2img
- support of multiple controlnet

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

2023-08-01 00:55 UTC, yike5460 commented on aws_extension/mme_utils.py
> +    print('default modules load fails')
in which case we may fail to load module, and what is the expected next step beside print?

2023-08-01 01:02 UTC, yike5460 commented on aws_extension/mme_utils.py
> +                download_and_update(model_type, f'{model["s3"]}/{model["model_name"]}')
what is the model[] schema, why s3/model_name are parallel key?

2023-08-01 01:03 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +                        # todo: these not need anymore
@AoyuQC please help to confirm

2023-08-01 01:04 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +                # controlnet_dropdown = gr.Dropdown(multiselect=True, label="ControlNet-Model", choices=sorted(get_controlnet_model_list()), elem_id="sagemaker_controlnet_model_dropdown")
delete directly if fully tested in controlnet

2023-08-01 01:05 UTC, yike5460 commented on aws_extension/test_mme_utils.py
> +        content = read_from_s3('s3://sd-release-test-sddreamboothtr-aigcbucketa457cb49-dhvez2qft7lj/txt2img/infer_v2/1690443798.119154/api_param.json')
this information must not exposed

2023-08-01 01:05 UTC, yike5460 commented on aws_extension/test_mme_utils.py
> +                    's3': 's3://sd-release-test-sddreamboothtr-aigcbucketa457cb49-dhvez2qft7lj/Stable-diffusion/checkpoint/release-test-01/67bfa613-4c53-471e-aeaf-ba7525884c88',
this information must not exposed

2023-08-01 01:15 UTC, yike5460 commented on dreambooth_on_cloud/create_model.py
> +        url = api_gateway_url + "checkpoints?status=Active"
is this a bug fix or feature change?
@NingLu check the API schema change

2023-08-01 01:16 UTC, yike5460 commented on infrastructure/src/main.ts
> +      'datasets',
what's the difference with 's' and without?

2023-08-01 01:17 UTC, yike5460 commented on infrastructure/src/main.ts
> +    const ddbTables = new Database(this, 'sd-ddb');
is this a new created ddb? what's the usage?

2023-08-01 01:19 UTC, yike5460 commented on infrastructure/src/sd-inference/inference-job-create-api.ts
> +        'kms:Decrypt',
why kms needed?

2023-08-01 01:20 UTC, yike5460 commented on infrastructure/src/sd-inference/inference-job-create-api.ts
> +        'arn:aws:s3:::*sagemaker*'],
is this a common usage to cover all uppercase/lowercase?

2023-08-01 01:23 UTC, yike5460 commented on infrastructure/src/sd-inference/inference-job-run-api.ts
> +    const runJobIntegration = new apigw.LambdaIntegration(
why inference run function need such template while inference create function don't?

2023-08-01 01:25 UTC, yike5460 commented on infrastructure/src/sd-inference/sd-async-inference-stack.ts
@guming3d please help to review the major change

2023-08-01 01:26 UTC, yike5460 commented on infrastructure/src/sd-inference/sd-sagemaker-inference-state-machine.ts
@guming3d please to review the major change

2023-08-01 01:27 UTC, yike5460 commented on infrastructure/src/sd-train/sd-train-deploy-stack.ts
main change in such file is variable renaming and position adjustment

2023-08-01 01:28 UTC, yike5460 commented on infrastructure/src/shared/database.ts
we need a update on existing ddb schema diagram

2023-08-01 01:29 UTC, yike5460 commented on install.sh
> -INITIAL_SUPPORT_COMMIT_ROOT=68f336bd994bed5442ad95bad6b6ad5564a5409a
why delete such marcos?

2023-08-01 01:29 UTC, yike5460 commented on middleware_api/lambda/inference/app.py
> -utils_endpoint_name = os.environ.get("SAGEMAKER_ENDPOINT_NAME")
where does this moved?

2023-08-01 01:31 UTC, yike5460 commented on middleware_api/lambda/inference_v2/test_inference_api.py
had been the test been done

2023-08-01 01:33 UTC, yike5460 commented on workshop/ec2.yaml
separate to another PR

2023-08-01 01:33 UTC, alvindaiyan commented on aws_extension/mme_utils.py
> +    print('default modules load fails')
when I write ut for the method, there will be an import error if we don't have the ui project unless we mock them.

2023-08-01 01:36 UTC, alvindaiyan commented on aws_extension/mme_utils.py
> +                download_and_update(model_type, f'{model["s3"]}/{model["model_name"]}')
the schema is https://github.com/alvindaiyan/stable-diffusion-aws-extension/blob/dev/middleware_api/lambda/inference_v2/_types.py#InvocationsRequest

2023-08-01 01:36 UTC, yike5460 reviewed
split PR into separate PRs including feature change, bug fix, format adjustment etc. with @guming3d @NingLu @AoyuQC as module reviewer

2023-08-01 01:37 UTC, alvindaiyan commented on aws_extension/sagemaker_ui.py
> +                # controlnet_dropdown = gr.Dropdown(multiselect=True, label="ControlNet-Model", choices=sorted(get_controlnet_model_list()), elem_id="sagemaker_controlnet_model_dropdown")
these need discussion as we don't have any other ui to show all uploaded models.

2023-08-01 01:39 UTC, alvindaiyan commented on infrastructure/src/main.ts
> +      'datasets',
get one dataset or train vs a collection of datasets and trains

2023-08-01 01:40 UTC, alvindaiyan commented on infrastructure/src/main.ts
> +    const ddbTables = new Database(this, 'sd-ddb');
put all ddb table in one place for easier management

2023-08-01 01:46 UTC, alvindaiyan commented on infrastructure/src/sd-inference/inference-job-create-api.ts
> +        'kms:Decrypt',
I copied code from other lambda, will check

2023-08-01 01:48 UTC, alvindaiyan commented on infrastructure/src/sd-inference/inference-job-run-api.ts
> +    const runJobIntegration = new apigw.LambdaIntegration(
I've a path variable for run function, so need this template to parse it, create one doesn't

2023-08-01 02:02 UTC, alvindaiyan commented on aws_extension/test_mme_utils.py
> +                    's3': 's3://sd-release-test-sddreamboothtr-aigcbucketa457cb49-dhvez2qft7lj/Stable-diffusion/checkpoint/release-test-01/67bfa613-4c53-471e-aeaf-ba7525884c88',
fixed

2023-08-01 02:26 UTC, alvindaiyan commented on install.sh
> -INITIAL_SUPPORT_COMMIT_ROOT=68f336bd994bed5442ad95bad6b6ad5564a5409a
merge conflicts are not done properly, will fix

2023-08-01 07:03 UTC, NingLu commented on infrastructure/src/sd-inference/inference-job-create-api.ts
> +        'arn:aws:s3:::*sagemaker*'],
s3 only allow lower case, so below two lines can be removed

'arn:aws:s3:::*SageMaker*',
'arn:aws:s3:::*Sagemaker*',

2023-08-01 07:27 UTC, NingLu commented on middleware_api/lambda/inference_v2/inference_api.py
After the PR is merged, which api will be invoked, v1 or v2? 
can we update the api based on the original v1 api, why do we need a new one

2023-08-01 07:27 UTC, NingLu commented on middleware_api/lambda/inference_v2/inference_api.py
> +def prepare_inference(raw_event, context):
Use a post and put method will cause the user to invoke twice to start an inference, can we call it only once just like the original inference api?

2023-08-01 07:27 UTC, NingLu commented on utils.py
> +    s3 = boto3.client('s3')
how about move it outside the function, so that no need to create a new s3 client once the function is called

2023-08-01 09:55 UTC, AoyuQC commented on aws_extension/mme_utils.py
> +                download_and_update(model_type, f'{model["s3"]}/{model["model_name"]}')
how can we get model s3 path without checkpoint info?

2023-08-01 09:58 UTC, AoyuQC commented on aws_extension/mme_utils.py
> +                download_and_update(model_type, f'{model["s3"]}/{model["model_name"]}')
did you ever test with different models? download_and_update(model_type, selected_model_name, selected_model_s3_pos) will take effect when the endpoint doesn't have a model in local environment and you have to download from s3

2023-08-01 09:59 UTC, AoyuQC commented on aws_extension/mme_utils.py
> +                download_and_update(model_type, f'{model["s3"]}/{model["model_name"]}')
shared.opts.sd_model_checkpoint = selected_models['Stable-diffusion'][0] this will be used later by reload_models.

2023-08-01 10:05 UTC, AoyuQC commented on scripts/api.py
> +        shared.opts.data.update(control_net_max_models_num=10)
why do we set control_net_max_models_num=10?

2023-08-01 10:05 UTC, AoyuQC requested changes
shared.opts.sd_model_checkpoint = selected_models['Stable-diffusion'][0] cannot be deleted, this will be used by sd_models.reload_model_weights()

2023-08-02 00:59 UTC, guming3d commented on middleware_api/lambda/inference_v2/inference_api.py
> +def prepare_inference(raw_event, context):
Only saw three api here, where is the other api?

2023-08-02 01:04 UTC, yike5460 commented on aws_extension/test_mme_utils.py
> +        import mme_utils
move to top

2023-08-02 01:06 UTC, yike5460 commented on infrastructure/src/main.ts
> +    const ddbTables = new Database(this, 'sd-ddb');
does this mean number of existing ddb will reduced, do we have doc to record the table update

2023-08-02 01:09 UTC, NingLu commented on scripts/api.py
> +            print(f'current version: dev')
Use logger to print log like below lines

2023-08-02 01:09 UTC, NingLu commented on scripts/api.py
> +                    if c == 'Infinity':
do we need to convert both strings to lower case?

2023-08-02 08:23 UTC, NingLu approved these changes

2023-08-02 08:38 UTC, guming3d approved these changes

2023-08-02 09:30 UTC, yike5460 approved these changes
looks good to me

2023-08-02 09:35 UTC, merged