feature: upload models from local to S3 directly
awslabs/stable-diffusion-aws-extension pull request #120
Opened 2023-08-07 05:43 UTC by o0OooO

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-07 12:59 UTC, alvindaiyan commented
What's the maximum file size and number for this feature?

2023-08-08 03:38 UTC, alvindaiyan requested changes

2023-08-08 07:30 UTC, yike5460 commented on scripts/main.py
> +                            print(f"change_model_type_value:{model_type}")
use console.log instead

2023-08-08 07:30 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +    # local_paths = [sd_checkpoints_path, textual_inversion_path, lora_path, hypernetwork_path, controlnet_model_path]
will such code block add back, delete if not

2023-08-08 07:31 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +    # print(f"Refresh checkpionts after upload...")
typo, checkpoints

2023-08-08 07:31 UTC, yike5460 commented on javascript/txt2img-config.js
> +let chunkSize = 1024 * 1024 * 1024; // 1GB chunk size, you can adjust this as needed.
no magic number

2023-08-08 07:33 UTC, yike5460 reviewed
make sure used/redundant code removed

2023-08-09 02:16 UTC, merged