feat: add inference job filter
awslabs/stable-diffusion-aws-extension pull request #121
Opened 2023-08-07 12:43 UTC by o0OooO

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-08 03:32 UTC, alvindaiyan requested changes

2023-08-08 03:37 UTC, alvindaiyan requested changes

2023-08-08 03:37 UTC, alvindaiyan commented on middleware_api/lambda/inference/app.py
> +                'checkpoint': checkpoint_name,
the new txt2img and img2img process is not using these code

2023-08-08 06:16 UTC, o0OooO commented on aws_extension/sagemaker_ui.py
> +
不是global的设置值不生效

2023-08-08 06:16 UTC, o0OooO commented on middleware_api/lambda/inference/app.py
> +                'checkpoint': checkpoint_name,
好的 我删掉～

2023-08-08 07:37 UTC, alvindaiyan commented on middleware_api/lambda/inference/app.py
> +                'checkpoint': checkpoint_name,
no delete pls, the api is still in use

2023-08-08 07:59 UTC, yike5460 commented
@o0OooO It's a good practice to squash or clean up commits with 'test with log' before opening a pull request to maintain a clean commit history.

2023-08-08 10:47 UTC, alvindaiyan approved these changes
details need to be tested more

2023-08-08 10:49 UTC, alvindaiyan requested changes
the code will not work with new inference api yet

2023-08-10 02:58 UTC, alvindaiyan approved these changes

2023-08-10 02:58 UTC, alvindaiyan commented on aws_extension/sagemaker_ui.py
> +                        modules.ui.create_refresh_button(sagemaker_endpoint_filter, update_sagemaker_endpoints, lambda: {"choices": sagemaker_endpoints}, "refresh_sagemaker_endpoints")
can we empty the selector after we select one?

2023-08-10 03:17 UTC, merged