fix: saving stable diffusion model error in dreambooth training
awslabs/stable-diffusion-aws-extension pull request #125
Opened 2023-08-08 04:48 UTC by outstandingcandy

Fix a saving stable diffusion model issue in dreambooth training by reinstall torchaudio.
Add debug log in sagemaker training image.
PS: training with default mixed precision setting (no) will fail in g5 instance, because of the cuda library version.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [*] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-08 07:42 UTC, alvindaiyan approved these changes
lgtm

2023-08-08 14:14 UTC, yike5460 commented on build_scripts/training/sagemaker_entrypoint.py
> +    os.system("df -h")
implemented with os agnostic function instead of shell script to make sure it also working on windows, refer to code to import library from utils module to implement the same function

2023-08-08 14:15 UTC, yike5460 requested changes
replace the shell script to common python code

2023-08-08 14:18 UTC, yike5460 commented on build_scripts/training/sagemaker_entrypoint.py
> +    os.system("df -h")
need to confirm if they always running inside linux like container in SageMaker?

2023-08-08 15:09 UTC, alvindaiyan commented on build_scripts/training/sagemaker_entrypoint.py
>  def test():
this test function should move out of this file

2023-08-08 15:09 UTC, alvindaiyan commented on build_scripts/training/sagemaker_entrypoint.py
> +    os.system("df -h")
yes, this file only should only run inside sagemaker

2023-08-09 03:24 UTC, yike5460 approved these changes

2023-08-09 03:24 UTC, merged