fix: check if downloads need tar -xvf files
awslabs/stable-diffusion-aws-extension pull request #167
Opened 2023-08-18 07:06 UTC by o0OooO

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-18 07:10 UTC, NingLu commented
We identified new issues on unchanged lines of code. Navigate to the Amazon CodeGuru Reviewer console to view the recommendations to fix them.

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +    file_type = subprocess.check_output(command, shell=True).decode('utf-8').strip()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f'./tools/s5cmd cp {prefix_name}* ./models/{model_type}/')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f"rm {tar_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f"rm {tar_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-08-18 07:10 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f"tar xvf {tar_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-08-18 07:53 UTC, alvindaiyan requested changes

2023-08-18 07:53 UTC, alvindaiyan commented on test/api_test/txt2img_api_test/txt2img_local_api_user1.py
> +request = InvocationsRequest(task='txt2img', username='test',param_s3='s3://stabledeffusion110-sds3aigcbucket7db76a0b-f8h2ckvcafgm/txt2img/infer_v2/068e4cb2-3cb3-41d6-8d37-1d9424940aa3/api_param.json
remove s3 info

2023-08-18 08:21 UTC, alvindaiyan commented
Looks like a group of (safetensor)files shares one checkpoint entry in the ddb table, I'm not sure if this works well and this is NOT how we want save models in the table originally.

2023-08-20 06:09 UTC, yike5460 requested changes

2023-08-20 06:09 UTC, yike5460 commented on aws_extension/mme_utils.py
> +        os.system(f"tar xvf {tar_name}")
It won't work on windows

2023-08-20 06:09 UTC, yike5460 commented on test/api_test/txt2img_api_test/_types.py
> +    # txt2img_payload: Optional[StableDiffusionTxt2ImgProcessingAPI]
Remove unused code

2023-08-20 06:09 UTC, yike5460 commented on test/api_test/txt2img_api_test/txt2img_local_api_user1.py
> +# checkpoint_info = {'Stable-diffusion': {'v2-1_768-ema-pruned.safetensors': 's3://stable-diffusion-aws-extension-aigcbucketa457cb49-xfyck6nj4vlo/Stable-diffusion/checkpoint/custom/13896019-1ba4-478a
Specific bucket name should never exposed

2023-08-21 02:28 UTC, o0OooO commented on aws_extension/mme_utils.py
> +        os.system(f"tar xvf {tar_name}")
这个是在镜像里执行的

2023-08-21 08:55 UTC, merged