feat: version upgrade solution
awslabs/stable-diffusion-aws-extension pull request #169
Opened 2023-08-18 17:54 UTC by Shellmode

## Description

Refer README.md

Fixes #165 (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-18 17:57 UTC, NingLu commented on version_upgrade/after_run_cf.py
> +    while all_done == False:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-08-18 17:57 UTC, NingLu commented on version_upgrade/after_run_cf.py
> +    subprocess.run(["aws", "s3", "sync", "s3://" + src_bucket_name, "s3://" + dst_bucket_name])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-08-18 17:57 UTC, NingLu commented on version_upgrade/after_run_cf.py
> +    subprocess.run(["aws", "s3", "sync", "s3://" + src_bucket_name, "s3://" + dst_bucket_name])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-08-20 06:03 UTC, yike5460 commented
Thanks for the feedback, the stack will only need to update instead of deletion if the DynamoDB schema kept unchanged.

2023-08-21 09:20 UTC, alvindaiyan commented
it's a good start to me, but we will do this through cfn instead

2023-08-21 09:24 UTC, alvindaiyan requested changes
This is a good script for temporary upgrade solution. We will update the cfn in the long run to accept the ddb table and s3 from previous deployment?

2023-08-31 08:42 UTC, closed without merging

2023-08-31 08:42 UTC, yike5460 commented
Closed for now due to new alternative raised.