feat: add upload api backend about uploading file to s3 from url directly
awslabs/stable-diffusion-aws-extension pull request #176
Opened 2023-08-29 05:40 UTC by o0OooO

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-08-29 05:43 UTC, NingLu commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        if event.params is not None and len(event.params) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-08-29 05:43 UTC, NingLu commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        checkpoint_params['created'] = str(datetime.datetime.now())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

Similar issue at line number 135.

2023-08-29 05:43 UTC, NingLu commented on middleware_api/lambda/model_and_train/common_tools.py
> +    with urllib.request.urlopen(url) as response:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-08-29 06:38 UTC, alvindaiyan requested changes

2023-08-29 06:38 UTC, alvindaiyan commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +x
??

2023-08-29 06:38 UTC, alvindaiyan commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +
add the url path comment like all others

2023-08-29 06:38 UTC, alvindaiyan commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +
we upload the file from backend and within aws network, so there is no need to do multipart, just use s3.upload

2023-08-29 06:38 UTC, alvindaiyan commented on middleware_api/lambda/model_and_train/common_tools.py
> +    logging.info(f"start multipart_upload_from_url:{url}, {s3_key}")
no need multipart upload, just s3.upload

2023-08-30 05:19 UTC, NingLu commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        checkpoint_params['created'] = str(datetime.datetime.now())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

Similar issue at line number 136.

2023-08-31 05:27 UTC, NingLu commented on middleware_api/lambda/inference_result_notification/app.py
> +            update_inference_job_table(inference_id, 'completeTime', str(datetime.now()))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-05 10:13 UTC, alvindaiyan commented on infrastructure/src/main.ts
> +      'upload_checkpoint',
Suggestion: prefer path to be checkpoints/upload_checkpoint. The reason is it will make us easier to manage resource permissions in future.

2023-09-05 10:14 UTC, alvindaiyan requested changes
need a UI component in WebUI to use the api. Other than that, it's good to go.

2023-09-07 05:47 UTC, o0OooO commented on infrastructure/src/main.ts
> +      'upload_checkpoint',
先和当前保持一致层级，后续咱们可以统一调整修改

2023-09-07 05:48 UTC, NingLu commented
We identified new issues on unchanged lines of code. Navigate to the Amazon CodeGuru Reviewer console to view the recommendations to fix them.

2023-09-07 05:52 UTC, NingLu commented on aws_extension/sagemaker_ui.py
> +            created = datetime.fromtimestamp(create_time)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-07 06:08 UTC, NingLu commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +        'arn:aws:s3:::*SageMaker*',
S3 bucket name only allows lower case, feel free to remove arn:aws:s3:::*SageMaker*' and 'arn:aws:s3:::*Sagemaker*'，这次可以先merge，等下次再删一下

2023-09-07 06:29 UTC, guming3d commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +def download_and_upload_models(url: str, base_key: str, fine_names: list, multipart_upload: dict):
is fine_names a typo? file_names?

2023-09-07 06:39 UTC, o0OooO commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +def download_and_upload_models(url: str, base_key: str, fine_names: list, multipart_upload: dict):
是的 已修改

2023-09-07 06:42 UTC, o0OooO commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +        'arn:aws:s3:::*SageMaker*',
好的

2023-09-07 07:12 UTC, guming3d approved these changes

2023-09-07 08:08 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +            ckpt_type = ckpt["type"]
what is the response scheme, do we also need to validate the "type" if none?

2023-09-07 08:16 UTC, yike5460 commented on aws_extension/sagemaker_ui.py
> +    log = "uploading……"
it's not a valid return, should return the response if error happened

2023-09-07 08:17 UTC, yike5460 commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +        'kms:Decrypt',
why kms involved?

2023-09-07 08:18 UTC, yike5460 commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +      memorySize: 10240,
reason to use 10G for simple upload task?

2023-09-07 08:22 UTC, NingLu commented on aws_extension/sagemaker_ui.py
> +        status = response.get('checkpoint', {}).get('status')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Potentially untrusted inputs reach a method on a `Response` ([`Flask`](https://flask.palletsprojects.com/en/2.0.x/api/#response-objects)) or an `HttpResponse` ([`django`](https://docs.djangoproject.com/en/3.2/ref/request-response/#django.http.HttpResponse)) object or are being used to create a `Cookie`. Verify that these inputs are properly sanitized to protect your code from cross-site scripting (XSS) attack and HTTP response splitting vulnerabilities. To learn more, see the [Common Weakness Enumeration](https://cwe.mitre.org/data/definitions/113.html)website and the [Open Web Application Security Project](https://owasp.org/www-community/attacks/HTTP_Response_Splitting) website.

2023-09-07 08:24 UTC, yike5460 commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        url = response.headers.get('Location')
error handling?

2023-09-07 08:26 UTC, yike5460 commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        ddb_service.put_items(table=checkpoint_table, entries=checkpoint.__dict__)
error handling?

2023-09-07 08:29 UTC, yike5460 commented on middleware_api/lambda/model_and_train/common_tools.py
> +        with concurrent.futures.ThreadPoolExecutor() as executor:
The code uses concurrent.futures.ThreadPoolExecutor() to upload parts concurrently. However, the response.read(end - start) is not thread-safe. We might run into issues if multiple threads try to read from the same response object simultaneously.

2023-09-07 08:29 UTC, yike5460 commented on middleware_api/lambda/model_and_train/common_tools.py
> +        upload_id = s3.create_multipart_upload(Bucket=bucket_name, Key=s3_key,
error handling ?

2023-09-07 08:30 UTC, yike5460 commented on middleware_api/lambda/model_and_train/common_tools.py
> +        s3.complete_multipart_upload(
error handling ?

2023-09-07 08:32 UTC, o0OooO commented on aws_extension/sagemaker_ui.py
> +    log = "uploading……"
已调整，增加成功的展示，但对于大部分情况：apigateway最大超时时间是29s,所以接口可能超时还没执行完，这个时候apigateway会提示{
    "message": "Endpoint request timed out"
} 所以提示的是uploading……

2023-09-07 08:33 UTC, yike5460 commented on middleware_api/lambda/model_and_train/common_tools.py
> +    s3 = boto3.client('s3')
add doc annotation for more better readability:
    """_summary_

    Args:
        xx (_type_): _description_

    Returns:
        int: _description_
    """

2023-09-07 08:34 UTC, o0OooO commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +      memorySize: 10240,
虽然数据没有落地直接从url流式读取到s3，但是这个过程会消耗内存，并且为了快速上传我是采用切片多线程上传，这样文件越大，可能分片越多线程数越多就比较吃内存，所以设置了个最大值

2023-09-07 08:40 UTC, o0OooO commented on javascript/txt2img-config.js
> +let filButtonClass = 'block gradio-html svelte-90oupt padded hide-container';
这里的样式变化主要是因为切换了上级gradio的组件从According变成了Tab，所以样式需要调整下手动写的html上传的那个组件才能行对齐，后续变动应该不会很大了，具体里面样式的class确实不是很懂，但我是对着浏览器逐步的试用它父级的样式调出来的比较复合预期的效果。删除的话 这块样式我刚才试了下 就又看上去不对劲儿了

2023-09-07 08:41 UTC, o0OooO commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        url = response.headers.get('Location')
这个是为了解决c站网址重定向的问题，为了拿到https://civitai.com/api/download/models/114163这种模型地址对应的真实的模型名称

2023-09-07 08:44 UTC, o0OooO commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        url = response.headers.get('Location')
已加容错处理

2023-09-07 08:49 UTC, o0OooO commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        ddb_service.put_items(table=checkpoint_table, entries=checkpoint.__dict__)
这个put_items方法中是我们封装的一层，对于失败的情况会打印日志并抛出异常，所以这里调用的时候外面包了trycatch，异常时候 就直接返回下面的记录失败的结果 查看模型的时候是从ddb里面取 所以应该ok

2023-09-07 08:57 UTC, NingLu commented on middleware_api/lambda/model_and_train/checkpoint_api.py
> +        checkpoint_params['created'] = str(datetime.datetime.now())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

Similar issue at line number 137.

2023-09-07 09:02 UTC, o0OooO commented on middleware_api/lambda/model_and_train/common_tools.py
> +        with concurrent.futures.ThreadPoolExecutor() as executor:
已修改

2023-09-07 09:10 UTC, o0OooO commented on middleware_api/lambda/model_and_train/common_tools.py
> +        upload_id = s3.create_multipart_upload(Bucket=bucket_name, Key=s3_key,
已添加

2023-09-08 04:46 UTC, NingLu commented on infrastructure/src/sd-train/checkpoint-upload-api.ts
> +      memorySize: 10240,
Better to test it in advance to determine how much memory does it need

2023-09-08 04:47 UTC, NingLu approved these changes

2023-09-08 04:47 UTC, NingLu commented on javascript/txt2img-config.js
> +let filButtonClass = 'block gradio-html svelte-90oupt padded hide-container';
Better to test it in advance to determine how much memory does it need

2023-09-11 06:51 UTC, o0OooO commented
> need a UI component in WebUI to use the api. Other than that, it's good to go.

2023-09-11 06:52 UTC, merged