feature: add diffusers image support
awslabs/stable-diffusion-aws-extension pull request #203
Opened 2023-09-25 01:50 UTC by AoyuQC

## Description

Add diffusers images (API+Job) as the default image for customers

## Type of change

Please delete options that are not relevant.

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/openpose/cv_ox_det.py
> +            if len(keep) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 52.

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/mmdet_wrapper.py
> +    if segm_result is not None and len(labels) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/roi_align.py
> +        return grad_input, None, None, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +        commit_history = subprocess.run(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_xl_reference.py
> +                if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/launch_utils.py
> +    result = subprocess.run(**run_kwargs)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/api.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/modules/cache.py
> +    global dump_cache_after
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 22, 25, 26, and 56.

2023-09-25 02:09 UTC, NingLu commented on build_scripts/job/dreambooth/webhook.py
> +            prompt += f"{i}: {p}\r\n"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/upfirdn2d.py
> +        return grad_input, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/controlnet.py
> +        if len(units) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/midas_net_custom.py
> +        if "expand" in self.blocks and self.blocks['expand'] == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +    checkpoint_info = checkpoint_aliases.get(model_checkpoint, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/bricks/upsample.py
> +    if upsample is nn.Upsample:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +        os.system(f"tar xvf {tar_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 02:09 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +    global models_path, script_path, ckpt_dir, device_id, disable_safe_unpickle, dataset_filename_word_regex, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 52 and 318.

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/adapter.py
> +        if self.down == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +            return result_gallery, generation_info if tabname != "extras" else html_info_x, html_info, html_log
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:09 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +            except:  # wandb 無効時
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:09 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 997.

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +                        image = processed.images[0] if len(processed.images) > 0 else None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +    checkpoint_info = checkpoint_aliases.get(search_string, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/utils.py
> +            raise Exception("Image dtype must be float32.")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 82.

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/correlation.py
> +        return output_size
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +    if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].device.type == 'mps':
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/dreambooth/utils/text_utils.py
> +def build_strict_tokens(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora.py
> +            if self.down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 1004 and 1007.

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/keypose/__init__.py
> +    global human_det, pose_model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/midas_net_custom.py
> +        if self.channels_last==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/launch_utils.py
> +                output = subprocess.check_output([git, '-C', subdir, 'pull', '--autostash'])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 87. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 229-250, lines 253-264 into separate functions.

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/gitpython_hack.py
> +        ret = subprocess.check_output(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if not iscrowd == None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/sagemaker_entrypoint.py
> +    return s3_input_path, s3_output_path, training_type, params
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_controlnet_reference.py
> +                    if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/get_data.py
> +            obj = tarfile.open(temp_save_path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *obj*. The resource is allocated by call *tarfile.open*. The resource is referenced at lines 75, 76. The resource is closed at line 76. There are other execution paths that do not contain closure statements, for example, when *requests.get()* throws an exception. To prevent this resource leak, close *obj* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:11 UTC, NingLu commented on build_scripts/job/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/ui_extra_networks.py
> +                    is_empty = len(os.listdir(x)) == 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:11 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/mixture_tiling.py
> +    return row_segment[0], row_segment[1], col_segment[0], col_segment[1]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/coco_evaluator.py
> +            raise Exception("Please run accumulate() first")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +                os.startfile(path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process without a shell. https://bandit.readthedocs.io/en/latest/plugins/b606_start_process_with_no_shell.html

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/masks.py
> +        assert len(bitmasks_list) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/progress.py
> +    global current_task
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +                sp.Popen(["wsl-open", path])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:13 UTC, NingLu commented on build_scripts/job/modules/safe.py
> +            if len(data_pkl_filenames) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/metrics.py
> +    return area_intersect, area_union, area_pred_label, area_label
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/layers/batch_norm.py
> +        if len(norm) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/progress.py
> +    return gr.update(), gr.update(), gr.update(), f"Couldn't restore progress for {id_task}: results either have been discarded or never were obtained"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/prompt_parser.py
> +        cached = cache.get(prompt, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +        code += f"""
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/coco_evaluation.py
> +            if len(s[s > -1]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/sd_samplers_common.py
> +class InterruptedException(BaseException):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

When creating a module that can raise multiple distinct errors, a common practice is to create a base class for exceptions defined by that module, and subclasses for different error conditions. We recommend that custom exceptions should inherit from `Exception` instead of `BaseException`.

[Learn more](https://docs.python.org/3/library/exceptions.html#BaseException)
[Learn more](https://docs.python.org/3/library/exceptions.html#Exception)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/modules/images.py
> +    for texts, allowed_width in zip(hor_texts + ver_texts, [width] * len(hor_texts) + [pad_left] * len(ver_texts)):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line numbers 194 and 196.

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/vit.py
> +    hooks = [0, 1, 8, 11] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/c2_model_loading.py
> +def convert_c2_detectron_names(weights):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 26. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 125-204 into a separate function.

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/vit.py
> +    hooks = [2, 5, 8, 11] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/nms.py
> +    nms_op = eval(nms_type)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if not annotation_file == None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/visualizer.py
> +        if class_names is not None and len(class_names) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/misc.py
> +    if subprocess.call(f'which {cmd}', shell=True) != 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are using a string to construct a shell command that invokes the shell explicitly via `shell=True`. This can be susceptible to shell injection [CWE 78](https://cwe.mitre.org/data/definitions/78.html). We recommend that you use `shlex.quote()` on Python 3.3+ and `pipes.quote()` on Python 3.2 and earlier to escape white space and shell meta-characters in strings that are used to construct shell commands.

[Learn more](https://docs.python.org/3/library/subprocess.html#security-considerations)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/diff_to_sd.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/sd_vae.py
> +    global base_vae, checkpoint_info
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/tokenizer.py
> +        merges = gzip.open(bpe_path).read().decode('utf-8').split('\n')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *gzip.open*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/train_dreambooth.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_onnx.py
> +            res[p][1] *= multiplier
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;multiplier&#39; (index: 1 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;start_position&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/env.py
> +        gcc = subprocess.check_output('gcc --version | head -n1', shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/fused_bias_leakyrelu.py
> +        return gradgrad_out, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/sd-scripts/library/model_util.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/train_dreambooth.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/utils.py
> +    return layer_1, layer_2, layer_3, layer_4
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +    os.system(f'./tools/s5cmd cp {model_s3_pos} ./')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line number 100.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/control_net_lllite.py
> +    input()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/roi_pool.py
> +        return grad_input, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/backbones/resnet.py
> +    def __init__(self,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 70 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 409-468 into a separate function.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_model_util.py
> +    return text_model1, text_model2, vae, unet, logit_scale, ckpt_info
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/binary/__init__.py
> +    img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;img&#39; (index: 0 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;bin_threshold&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/utils.py
> +    exec(f"pretrained.model.{function_name}(x)")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/vit.py
> +        exec(f"pretrained.act_postprocess{s + 1}=value")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    if down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 664 and 669.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/datasets/pipelines/transforms.py
> +        return crop_y1, crop_y2, crop_x1, crop_x2
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/sd-scripts/gen_img_diffusers.py
> +            ts_str = time.strftime("%Y%m%d%H%M%S", time.localtime())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use the `datetime` module for time zone conversions. The older `time` module doesn&#39;t work consistently with multiple time zones and shouldn&#39;t be used.

[Learn more](https://docs.python.org/3/library/time.html#module-time.)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/vit.py
> +        exec(f"pretrained.act_postprocess{s + 1}=value")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/upscaler.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/modules/pix2pixhd.py
> +        if len(manual_block_spec) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/utils.py
> +    exec(f"glob = pretrained.model.{function_name}(x)")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py
> +            if "bbox" in obj and len(obj["bbox"]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 169.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +        sha = hashlib.sha1(v).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +def pred_squares(image,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 231 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 123-134 into a separate function.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/esrgan_model.py
> +    return in_nc, out_nc, nf, nb, plus, scale
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/job/dreambooth/train_dreambooth.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/rotated_coco_evaluation.py
> +        assert len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/dataset.py
> +                raise Exception("interrupted")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/roiaware_pool3d.py
> +        return None, None, grad_in, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:15 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/collect_env.py
> +                    nvcc = subprocess.check_output("'{}' -V".format(nvcc), shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:16 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/generation_parameters_copypaste.py
> +                v = params.get(key, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    if isinstance(model_name, list) and len(model_name) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +                self.init_img_hash = hashlib.md5(img.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/__init__.py
> +        cfg = yaml.safe_load(open(config_path, 'rt'))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *builtins.open*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/hooks/optimizer.py
> +        if len(params) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/__init__.py
> +    global model, pix2pixmodel
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/__init__.py
> +    except Exception as e:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:16 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    if (up_lr_weight != None and len(up_lr_weight) > max_len) or (down_lr_weight != None and len(down_lr_weight) > max_len):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 621, 625, 627, 630, 632, 638, and 644.

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/modulated_deform_conv.py
> +        return (grad_input, grad_offset, grad_mask, grad_weight, grad_bias,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/postprocessing.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Continue detected. https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/dataset_mappers/oneformer_unified_dataset_mapper.py
> +        if len(masks) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +    return url, code, gr.CheckboxGroup.update(choices=tags), '', ''
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/models/diffusion/ddpm_edit.py
> +        return fold, unfold, normalization, weighting
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/dataset_mappers/coco_unified_new_baseline_dataset_mapper.py
> +        if len(masks) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sai_model_spec.py
> +        title = metadata.get(MODELSPEC_TITLE, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/logger.py
> +    last_logged = _LOG_TIMER.get(key, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +                    if len(self.bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 697.

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 02:16 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +    os.system(f"tar cvf {model_name} {models_path[model_type]}/{model_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line number 105.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/__init__.py
> +    except Exception as e:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/utils.py
> +        return self.models_ref.get(model_name)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `get` method without a default argument to return the value of a key in a dictionary. We recommended that you use a default argument so that if the value for your key is not found, a default value is returned. If a default value is not provided and the key is not found, then `None` is returned.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/tracing.py
> +                    eval(condition, caller_frame.f_globals, caller_frame.f_locals), message
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

If you do not have absolute control over the contents of the string passed to the `eval()` function, they might be maliciously used to execute an arbitrary function such as `__import__(&#39;os&#39;).system(&#34;rm -rf $HOME&#34;)`. If the string is expected to only contain literals, consider using the `ast.literal_eval()` method to safely evaluate strings containing Python values from untrusted sources.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-use-strings-to-call-functions-methods)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/sd_vae.py
> +    vae_from_options = vae_dict.get(shared.opts.sd_vae, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/get_data.py
> +        self.url = url_dict.get(technique.lower())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `get` method without a default argument to return the value of a key in a dictionary. We recommended that you use a default argument so that if the value for your key is not found, a default value is returned. If a default value is not provided and the key is not found, then `None` is returned.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/svd_merge_lora.py
> +                v2 = lora_metadata.get(train_util.SS_METADATA_KEY_V2, None)  # return string
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 56.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/esrgan_model.py
> +            raise Exception("The file is not a recognized ESRGAN model.")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/dreambooth/train_dreambooth.py
> +                    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +        sha = hashlib.sha1(v).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +    os.system(f"tar cvf {model_name} {models_path[model_type]}/{model_name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line number 105.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/images.py
> +    if items.get("Software", None) == "NovelAI":
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/run.py
> +    global first_execution
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 188.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/env.py
> +        gcc = subprocess.check_output('gcc --version | head -n1', shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/gen_img_diffusers.py
> +                        raw_prompt = input()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/api/utils.py
> +                raise Exception('failed at multipart')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_lpw_stable_diffusion.py
> +            return text_embeddings, text_pool, uncond_embeddings, uncond_pool
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 663.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora.py
> +    return block_dims, block_alphas, conv_block_dims, conv_block_alphas
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return "", "", "", 0, 0, "", "", "", "", res, "", err_msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 977, 992, and 1005.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/modulated_deform_conv.py
> +        return (grad_input, grad_offset, grad_mask, grad_weight, grad_bias,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/tiled_upscaling.py
> +    return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/keypoint_head.py
> +        global _TOTAL_SKIPPED
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +                        raw_prompt = input()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/image_list.py
> +        assert len(tensors) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/vit.py
> +    return layer_1, layer_2, layer_3, layer_4
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/backbones/resnet.py
> +    def __init__(self,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 70 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 409-468 into a separate function.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/losses/lovasz_loss.py
> +    if len(labels) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/segmentors/base.py
> +        for loss_name, loss_value in losses.items():
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line number 190.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/utils.py
> +        return host
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `break`, `continue` and `return` statements in a `finally` block will result in masking of unhandled exceptions from the `try`, `else`, and `except` blocks. If the `finally` block includes a `return` statement, the returned value will be the one from the return statement of the `finally` block, not the `try` block.

[Learn more](https://docs.python.org/3/library/exceptions.html#built-in-exceptions)
[Learn more](https://docs.python.org/3/tutorial/errors.html)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/image/io.py
> +        buff = io.BytesIO(content)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the following resource: *buff*. The resource is allocated by call *io.BytesIO*. Currently, there are execution paths that do not contain closure statements, for example, when *open()* throws an exception. To prevent this resource leak, close *buff* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/logger.py
> +    last_logged = _LOG_TIMER.get(key, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if not p.useSegm is None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/rotated_boxes.py
> +        if len(boxes_list) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/_functions.py
> +        raise Exception(f'Unknown type {type(output)}.')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:17 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +    return latents, original_size, crop_ltrb, flipped_latents
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/dataset_mappers/oneformer_unified_dataset_mapper.py
> +                if not np.all(mask == False):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/sdxl_merge_lora.py
> +                v2 = lora_metadata.get(train_util.SS_METADATA_KEY_V2, None)  # returns string, SDXLはv2がないのでFalseのはず
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 131.

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +    if len(checkpoints_list) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/vit.py
> +    return layer_1, layer_2, layer_3, layer_4
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_xl.py
> +        if len(text_encoder_state_dict) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 1242.

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/dpt_depth.py
> +        if self.channels_last == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/blocks.py
> +    if expand==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/gfpgan_model.py
> +    elif len(models) != 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/dataset_mappers/coco_unified_new_baseline_dataset_mapper.py
> +                if not np.all(mask == False):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/gfpgan_model.py
> +    global loaded_gfpgan_model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/rotated_fast_rcnn.py
> +            has_gt = len(targets_per_image) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/class_names.py
> +            labels = eval(alias2name[dataset] + '_palette()')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/clip/__init__.py
> +    global clip_proc, clip_vision_model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/job/dreambooth/utils/gen_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/learn_schedule.py
> +            raise Exception('Invalid learning rate schedule. It should be a number or, for example, like "0.001:100, 0.00001:1000, 1e-5:10000" to have lr of 0.001 until step 100, 0.00001 until 1000,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_reference.py
> +                    if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/bricks/norm.py
> +    cfg_.setdefault('eps', 1e-5)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/__init__.py
> +    global mlsdmodel
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_reference.py
> +                    if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:18 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/options/base_options.py
> +            message += '{:>25}: {:<30}{}\n'.format(str(k), str(v), comment)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/controlnet_ui/controlnet_ui_group.py
> +            return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/ros/midas_cpp/scripts/listener_original.py
> +        if self.show_output==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 42 and 43.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py
> +            if "bbox" in obj and len(obj["bbox"]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 169.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +            [k if k == v else f'{k}: {f"{v}" if "," in str(v) else v}' for k, v in generation_params.items()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/modules/txt2img.py
> +    return processed.images, generation_info_js, plaintext_to_html(processed.info), plaintext_to_html(processed.comments, classname="comments")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/segmentors/base.py
> +        for loss_name, loss_value in losses.items():
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line number 190.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/cityscapes.py
> +                if len(polygons) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/collect_env.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/leres/depthmap.py
> +            message += '{:>25}: {:<30}{}\n'.format(str(k), str(v), comment)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +        possible_matches = self.ids_lookup.get(token, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/modules/networks.py
> +    networks_on_disk = [available_network_aliases.get(name, None) for name in names]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line numbers 208 and 213.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/modules/pix2pixhd.py
> +        if len(manual_block_spec) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/testing.py
> +                if len(tval.shape) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/image_list.py
> +        assert len(tensors) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train_textual_inversion.py
> +        return sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, [text_encoder1, text_encoder2], vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/job/dreambooth/dataclasses/db_config.py
> +            raise Exception(f"shared_diffusers_path is \"{self.shared_diffusers_path}\" but use_lora is false")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    if down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 664 and 669.

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/modeling/pixel_decoder/msdeformattn.py
> +        return self.mask_features(out[-1]), out[0], multi_scale_features, spatial_shapes, level_start_index
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:19 UTC, NingLu commented on build_scripts/api/modules/safe.py
> +        raise Exception(f"bad file inside {filename}: {name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +def load_coco_json(json_file, image_root, dataset_name=None, extra_annotation_keys=None):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 34. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 126-133, lines 135-142, lines 144-227 into separate functions.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/controlnet.py
> +        if len(Script.model_cache) > 0 and len(Script.model_cache) >= shared.opts.data.get("control_net_model_cache_size", 2):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/safe.py
> +        raise Exception(f"bad file inside {filename}: {name}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/yaml_handler.py
> +        return yaml.load(file, **kwargs)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load(). https://bandit.readthedocs.io/en/latest/plugins/b506_yaml_load.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/evaluator.py
> +        stack.enter_context(torch.no_grad())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *no\_grad*. The resource is allocated by call *torch.no_grad*. Currently, there are execution paths that do not contain closure statements, for example, when *ExitStack.enter\_context()* throws an exception. To prevent this resource leak, close the object returned by *no\_grad()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion.py
> +            res[p][1] *= multiplier
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;multiplier&#39; (index: 1 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;start_position&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/safe.py
> +        raise Exception(f"global '{module}/{name}' is forbidden")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +    current_branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=shared.extension_path,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/utils.py
> +        return self.models_ref.get(model_name)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `get` method without a default argument to return the value of a key in a dictionary. We recommended that you use a default argument so that if the value for your key is not found, a default value is returned. If a default value is not provided and the key is not found, then `None` is returned.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/pickle_handler.py
> +        kwargs.setdefault('protocol', 2)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/pickle_handler.py
> +        kwargs.setdefault('protocol', 2)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/images.py
> +        'date': lambda self: datetime.datetime.now().strftime('%Y-%m-%d'),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/mixture_tiling.py
> +    return px_row_init // 8, px_row_end // 8, px_col_init // 8, px_col_end // 8
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas.py
> +        if len(self.handles) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/controlnet_ui/controlnet_ui_group.py
> +            return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    return block_dims, block_alphas, conv_block_dims, conv_block_alphas
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/masks.py
> +        assert len(polymasks_list) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/sd-scripts/train_network.py
> +        return model_util.get_model_version_str_for_sd1_sd2(args.v2, args.v_parameterization), text_encoder, vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/demo/visualizer.py
> +        if len(empty_ids) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/swin2.py
> +    hooks = [1, 1, 17, 1] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/sd_text2img_k_diffusion.py
> +        if kwargs.get("cond", None) is not None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +                    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 137.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/images.py
> +            if len(upscalers) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/masking.py
> +    return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train_control_net_lllite.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 69. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 148-164, lines 167-178 into separate functions.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/transforms/transform.py
> +        if len(coords) == 0 or self.angle % 360 == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/images.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/pickle_handler.py
> +        return pickle.load(file, **kwargs)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/sd-scripts/gen_img_diffusers.py
> +            if noise == None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/collect_env.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/coco_evaluator.py
> +            if len(s[s > -1]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/_functions.py
> +        raise Exception(f'Unknown type {type(input)}.')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                self.init_img_hash = hashlib.md5(img.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 02:20 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/compat.py
> +        if len(cur) == 0 and len(key_seq) > 1:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/losses/lovasz_loss.py
> +    if len(labels) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/collect_env.py
> +                cxx = subprocess.check_output("'{}' --version".format(cxx), shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/keypoint_head.py
> +        global _TOTAL_SKIPPED
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/metrics.py
> +    for metric in metrics:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line number 312.

2023-09-25 02:21 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/testing.py
> +    buffer = io.BytesIO()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the following resource: *buffer*. The resource is allocated by call *io.BytesIO*. Currently, there are execution paths that do not contain closure statements, for example, when *jit.save()* throws an exception. To prevent this resource leak, close *buffer* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_tensorrt_inpaint.py
> +        return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/json_handler.py
> +        kwargs.setdefault('default', set_default)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/ui_extra_networks_user_metadata.py
> +        return html.escape(name), user_metadata.get('description', ''), table, self.get_card_html(name), user_metadata.get('notes', '')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/dataset.py
> +                raise Exception("interrupted")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_xl.py
> +    return prompt_embeds, negative_prompt_embeds, pooled_prompt_embeds, negative_pooled_prompt_embeds
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +        latent_scale_mode = shared.latent_upscale_modes.get(self.hr_upscaler, None) if self.hr_upscaler is not None else shared.latent_upscale_modes.get(shared.latent_upscale_default_mode, "nearest")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/networks.py
> +    if len(loaded_networks) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +def pred_squares(image,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 231 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 123-134 into a separate function.

2023-09-25 02:21 UTC, NingLu commented on build_scripts/job/dreambooth/train_dreambooth.py
> +                    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/file_client.py
> +        value_buf = urlopen(filepath).read()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/sysinfo.py
> +    text = text.replace(checksum_token, h.hexdigest())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To improve your code&#39;s security, use a password hashing function, such as the key derivation and stretching algorithm, the [PHC](https://password-hashing.net/) or [Argon2](https://password-hashing.net/#argon2), with the correct time and memory cost parameters. Avoid using the less secure `BLAKE2`, `MD5`, `SHA-1`, `SHA-256` and `SHA-3` hash functions for user passwords. 

 [CWE 916](https://cwe.mitre.org/data/definitions/916.html).

[Learn more](https://docs.python.org/3/library/hashlib.html#key-derivation)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    return block_dims, block_alphas, conv_block_dims, conv_block_alphas
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/postprocessing.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Continue detected. https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html

2023-09-25 02:21 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/torchscript_patch.py
> +        StandardROIHeads.__annotations__["mask_on"] = torch.jit.Final[bool]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It seems that you used an arbitrary value while setting the type using `__annotations__`. This value is evaluated when `typing.get_type_hints` is invoked to receive annotations, which can lead to invocation of arbitrary code. We recommend that you set the type statically, or set type dynamically only if you trust the type.

[Learn more](https://cwe.mitre.org/data/definitions/95.html)

Similar issue at line number 384.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/ros/midas_cpp/scripts/listener_original.py
> +        if self.show_output==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 42 and 43.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +                self.init_img_hash = hashlib.md5(img.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/vit.py
> +    hooks = [0, 1, 8, 11] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/utils/config.py
> +    config_version = overwrite_kwargs.get("config_version", None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/webhook.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/ui_extra_networks_user_metadata.py
> +                ('Modified: ', datetime.datetime.fromtimestamp(stats.st_mtime).strftime('%Y-%m-%d %H:%M')),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/hypernetworks/hypernetwork.py
> +                        image = processed.images[0] if len(processed.images) > 0 else None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/models/diffusion/uni_pc/uni_pc.py
> +        use_predictor = len(D1s) > 0 and x_t is None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 682.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/c2_model_loading.py
> +    if len(matched_model_keys) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/datasets/register_coco_panoptic_annos_semseg.py
> +def load_coco_instance_json(json_file, image_root, dataset_name=None):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 34. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 106-113, lines 115-122, lines 124-207 into separate functions.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/_functions.py
> +        raise Exception(f'Unknown type {type(input)}.')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/batch_hijack.py
> +    return any_unit_is_batch, batches, output_dir, input_file_names
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/layers/deform_conv.py
> +        return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/ui.py
> +    return seed, reuse_seed, subseed, reuse_subseed, subseed_strength, seed_resize_from_h, seed_resize_from_w, seed_checkbox
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if not cocoGt is None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +    return latents, original_size, crop_ltrb, flipped_latents
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/collate.py
> +def collate(batch, samples_per_gpu=1):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 29. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/version_utils.py
> +    out = subprocess.Popen(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/class_names.py
> +            labels = eval(alias2name[dataset] + '_classes()')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +                sp.Popen(["wsl-open", path])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/shared.py
> +            [create_const_fill_op(name, blob, device_option=device_options.get(name, None))]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                raise Exception(f"could not find upscaler named {self.hr_upscaler}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/datasets/cityscapes.py
> +            result = np.load(result)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the following resource: *result*. The resource is allocated by call *numpy.load*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close *result* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +            raise Exception("Please run accumulate() first")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/checkpoint.py
> +    if len(err_msg) > 0 and rank == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/midas_net_custom.py
> +        if self.channels_last==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/codeformer_model.py
> +                if len(model_paths) != 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/common.py
> +        return pickle.loads(bytes)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/poolers.py
> +        if len(box_lists) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/pipeline_fabric.py
> +            if liked and len(liked) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 617.

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/next_vit.py
> +    hooks = [2, 6, 36, 39] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:22 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/blocks.py
> +        if self.expand==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +        if model_url is not None and len(output) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/job/lora_diffusion/extra_networks.py
> +    if len(loras) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/modeling/backbone/swin.py
> +            return x, H, W, x_down, Wh, Ww
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 454.

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_reference.py
> +                if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/upscaler.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/misc.py
> +    if subprocess.call(f'which {cmd}', shell=True) != 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:23 UTC, NingLu commented on build_scripts/job/sd-scripts/library/config_util.py
> +    info += dedent(f"""\
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line numbers 452, 471, and 477.

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/cityscapes_panoptic.py
> +        image_file = image_dict.get(ann["image_id"], None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/ui.py
> +    return prompt, prompt_styles, negative_prompt, submit, button_interrogate, button_deepbooru, prompt_style_apply, save_style, paste, extra_networks_button, token_counter, token_button, negative_to
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/sync_bn.py
> +        return grad_input, None, None, grad_weight, grad_bias, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/job/dreambooth/sd_to_diff.py
> +        original_config_file = get_config_file(train_unfrozen, v2=is_512 == False, prediction_type=prediction_type)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/gfpgan_model.py
> +    global loaded_gfpgan_model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/job/modules/safe.py
> +        raise Exception(f"global '{module}/{name}' is forbidden")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/cascade_rcnn.py
> +            if len(targets_per_image) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/modules/generation_parameters_copypaste.py
> +    if len(text) == 0 or text[0] != '"' or text[-1] != '"':
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/adapter.py
> +        if in_c != out_c or sk==False:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 214 and 220.

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/logger.py
> +    last_logged = _LOG_TIMER.get(key, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/_functions.py
> +        raise Exception(f'Unknown type {type(output)}.')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:23 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_minimal_inference.py
> +            seed = input("seed: ")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 02:23 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/modulated_deform_conv.py
> +        return (grad_input, grad_offset, grad_mask, grad_weight, grad_bias,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    return block_dims, block_alphas, conv_block_dims, conv_block_alphas
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/modules/img2img.py
> +                filename += f"-{n}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/distributed_deprecated.py
> +        if len(module_states) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 48.

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/sd-scripts/train_network.py
> +        return model_util.get_model_version_str_for_sd1_sd2(args.v2, args.v_parameterization), text_encoder, vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/proposal_generator/rrpn.py
> +            if len(gt_boxes_i) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 76. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/normalbae/models/submodules/efficientnet_repo/setup.py
> +exec(open('geffnet/version.py').read())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *codecs.open*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/normalbae/models/submodules/efficientnet_repo/setup.py
> +exec(open('geffnet/version.py').read())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/modules/ui_gradio_extensions.py
> +        head += stylesheet(cssfile)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/modules/ui_settings.py
> +                    section_must_be_skipped = item.section[0] is None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +def convert_to_coco_dict(dataset_name):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 25. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/wildcard_stable_diffusion.py
> +def grab_wildcard_values(wildcard_option_dict: Dict[str, List[str]] = {}, wildcard_files: List[str] = []):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Default values in Python are created exactly once, when the function is defined. If that object is changed, like the `wildcard_option_dict` object in this example, subsequent calls to the function will refer to the changed object, leading to confusion. We recommend that you set the default value to `None`, then check inside the function if the parameter is `None` before creating the desired mutable object.

[Learn more](https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/job/modules/cache.py
> +    global dump_cache_after
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 24, 27, 28, and 58.

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/mask_head.py
> +        if len(instances_per_image) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 71.

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +        sha = hashlib.sha1(v).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/info.py
> +    if len(paths) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:24 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas.py
> +        if len(self.handles) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/video/processing.py
> +    subprocess.call(cmd, shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/layers/batch_norm.py
> +                if new_child is not child:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/sd-scripts/finetune/blip/blip.py
> +        assert(len(msg.missing_keys)==0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/backbones/unet.py
> +    def __init__(self,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 72 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 292-331, lines 334-374 into separate functions.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line numbers 129, 135, 141, 147, and 153.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/bricks/context_block.py
> +        assert len(fusion_types) > 0, 'at least one fusion should be used'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/example/chatgpt.py
> +    tokens = history_memory.split()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;history_memory&#39; (index: 0 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;keep_last_n_words&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/autocrop.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Continue detected. https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/config.py
> +                if len(duplicate_keys) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/shared.py
> +        if len(non_none_types) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/boxes.py
> +        if len(boxes_list) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/build.py
> +        proposals = pickle.load(f, encoding="latin1")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/projects/deeplab/semantic_seg.py
> +        self.decoder_only     = num_classes is None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/image/geometric.py
> +    cmin[0::2] = img_shape[1] - 1
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;img_shape&#39; (index: 1 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;bboxes&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/extras.py
> +        info += f"""
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/utils/flops_counter.py
> +    if len(input) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +            exec(compile(content, cur_file, "exec"), module.__dict__)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/engine/launch.py
> +    sock.close()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To close a socket and immediately release its associated resources, call `socket.shutdown()` before you call `socket.close()`.

[Learn more](https://docs.python.org/3/library/socket.html#socket.close)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +                    value = eval(value, {})
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/sdxl_merge_lora.py
> +                v2 = lora_metadata.get(train_util.SS_METADATA_KEY_V2, None)  # returns string, SDXLはv2がないのでFalseのはず
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 131.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if not p.useSegm is None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +            if self.down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 1024 and 1027.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/utils.py
> +        return host
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `break`, `continue` and `return` statements in a `finally` block will result in masking of unhandled exceptions from the `try`, `else`, and `except` blocks. If the `finally` block includes a `return` statement, the returned value will be the one from the return statement of the `finally` block, not the `try` block.

[Learn more](https://docs.python.org/3/library/exceptions.html#built-in-exceptions)
[Learn more](https://docs.python.org/3/tutorial/errors.html)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        msg += f"<br>{key}: {log_dict[key]}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/projects/deeplab/semantic_seg.py
> +        self.decoder_only     = num_classes is None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +    except Exception as e:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/vit.py
> +    if use_vit_only == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line number 375.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/dataset_mappers/oneformer_unified_dataset_mapper.py
> +                if not np.all(mask == False):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/ui_settings.py
> +                    section_must_be_skipped = item.section[0] is None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                self.init_img_hash = hashlib.md5(img.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/api/utils.py
> +        return self.models_ref.get(model_name)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `get` method without a default argument to return the value of a key in a dictionary. We recommended that you use a default argument so that if the value for your key is not found, a default value is returned. If a default value is not provided and the key is not found, then `None` is returned.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +                sp.Popen(["open", path])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +                raise Exception(f"could not find upscaler named {self.hr_upscaler}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/bricks/context_block.py
> +        assert len(fusion_types) > 0, 'at least one fusion should be used'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/pickle_handler.py
> +        return pickle.load(file, **kwargs)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +                urlretrieve(img['coco_url'], fname)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-09-25 02:25 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/class_names.py
> +            labels = eval(alias2name[dataset] + '_classes()')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/modules/images.py
> +    if items.get("Software", None) == "NovelAI":
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/adapter.py
> +        if in_c != out_c or sk==False:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 214 and 220.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +    if len(coco_annotations) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/blocks.py
> +        if self.bn==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line number 368.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if not p.useSegm is None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use `is not` operator rather than `not ... is` because it is more readable and makes your code easier to understand.

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=Use%20is%20not)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/_functions.py
> +        raise Exception(f'Unknown type {type(output)}.')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/base_runner.py
> +            if len(hook_infos) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_lpw_stable_diffusion.py
> +            return text_embeddings, text_pool, uncond_embeddings, uncond_pool
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 663.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/swin.py
> +    hooks = [1, 1, 17, 1] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/visualizer.py
> +            message += '%s: %.3f ' % (k, v)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/keypoints.py
> +        assert len(keypoints_list) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +                info = opts.data_labels.get(key, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/dataset.py
> +    def __init__(self, data_root, width, height, repeats, flip_p=0.5, placeholder_token="*", model=None, cond_model=None, device=None, template_file=None, include_cond=False, batch_size=1, gradient_s
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;*&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/lvis_evaluation.py
> +        if len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +    current_branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=shared.extension_path,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_reference.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 47 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 163-796 into a separate function.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/utils.py
> +        return host
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `break`, `continue` and `return` statements in a `finally` block will result in masking of unhandled exceptions from the `try`, `else`, and `except` blocks. If the `finally` block includes a `return` statement, the returned value will be the one from the return statement of the `finally` block, not the `try` block.

[Learn more](https://docs.python.org/3/library/exceptions.html#built-in-exceptions)
[Learn more](https://docs.python.org/3/tutorial/errors.html)

2023-09-25 02:26 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return "", "", "", 0, 0, "", "", "", "", res, "", err_msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 977, 992, and 1005.

2023-09-25 02:26 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/pickle_handler.py
> +        kwargs.setdefault('protocol', 2)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/sd-scripts/train_textual_inversion_XTI.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 73. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 171-187 into a separate function.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +                urlretrieve(img['coco_url'], fname)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +                raise Exception(f"could not find upscaler named {self.hr_upscaler}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 378.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +            if self.down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 1024 and 1027.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/tracing.py
> +                    eval(condition, caller_frame.f_globals, caller_frame.f_locals), message
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of possibly insecure function - consider using safer ast.literal_eval. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/utils/gen_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 203.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_onnx.py
> +            if len(weights[i]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/backbones/levit.py
> +    hooks = [3, 11, 21] if hooks == None else hooks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/blocks.py
> +        if self.bn==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +stdout: {result.stdout.decode(encoding="utf8", errors="ignore") if len(result.stdout) > 0 else '<empty>'}
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 123.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/modules/safe.py
> +            if len(data_pkl_filenames) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/meta_arch/retinanet.py
> +            if len(gt_per_image) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/dpt_depth.py
> +        if self.channels_last == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/pascal_voc.py
> +            tree = ET.parse(f)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using xml.etree.ElementTree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.parse with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b313-b320-xml-bad-elementtree

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/utils.py
> +            raise Exception("Not a PFM file: " + path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 38.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/adapter.py
> +        if in_c != out_c or sk==False:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 174 and 181.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +                    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 137.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/sd-scripts/finetune/blip/blip.py
> +        assert(len(msg.missing_keys)==0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/cityscapes.py
> +    pool = mp.Pool(processes=max(mp.cpu_count() // get_world_size() // 2, 4))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the following resource: *pool*. The resource is allocated by call *multiprocessing.Pool*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close *pool* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/helpers/version_helper.py
> +        commit_history = subprocess.run(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/layers/batch_norm.py
> +                if new_child is not child:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/normalbae/models/submodules/efficientnet_repo/geffnet/conv2d_layers.py
> +    kwargs.setdefault('bias', False)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/structures/instances.py
> +        assert len(instance_lists) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/rotated_coco_evaluation.py
> +        if len(gt) == 0 and len(dt) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/config.py
> +                if len(duplicate_keys) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/mask_head.py
> +        if len(instances_per_image) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 71.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return "", "", "", 0, 0, "", "", "", "", res, "", err_msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 977, 992, and 1005.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/shared.py
> +            [create_const_fill_op(name, blob, device_option=device_options.get(name, None))]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/lvis_evaluation.py
> +        if len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/multi_scale_deform_attn.py
> +        return grad_value, None, None, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +                exec(compile(content, filename, "exec"), module_namespace)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of exec detected. https://bandit.readthedocs.io/en/latest/plugins/b102_exec_used.html

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/env.py
> +                    f'"{nvcc}" -V | tail -n1', shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/get_data.py
> +            obj = ZipFile(temp_save_path, 'r')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *obj*. The resource is allocated by call *zipfile.ZipFile*. The resource is referenced at lines 75, 76. The resource is closed at line 76. There are other execution paths that do not contain closure statements, for example, when *requests.get()* throws an exception. To prevent this resource leak, close *obj* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 02:27 UTC, NingLu commented on build_scripts/api/modules/sysinfo.py
> +    h = hashlib.sha256(replaced.encode("utf8"))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To improve your code&#39;s security, use a password hashing function, such as the key derivation and stretching algorithm, the [PHC](https://password-hashing.net/) or [Argon2](https://password-hashing.net/#argon2), with the correct time and memory cost parameters. Avoid using the less secure `BLAKE2`, `MD5`, `SHA-1`, `SHA-256` and `SHA-3` hash functions for user passwords. 

 [CWE 916](https://cwe.mitre.org/data/definitions/916.html).

[Learn more](https://docs.python.org/3/library/hashlib.html#key-derivation)

Similar issue at line number 71.

2023-09-25 02:27 UTC, NingLu commented on build_scripts/job/dreambooth/utils/gen_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train_textual_inversion.py
> +        return sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, [text_encoder1, text_encoder2], vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +            raise Exception('datasetType not supported')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/tiled_upscaling.py
> +    return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/cascade_rcnn.py
> +            if len(targets_per_image) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/dreambooth/diff_to_sd.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/coco_evaluator.py
> +                if len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +        raise Exception(f'Extension with this URL is already installed: {url}')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/modeling/pixel_decoder/msdeformattn.py
> +        return self.mask_features(out[-1]), out[0], multi_scale_features, spatial_shapes, level_start_index
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +    def __init__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 159 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 181-300 into a separate function.

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/utils/config.py
> +    config_version = overwrite_kwargs.get("config_version", None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/c2_model_loading.py
> +def align_and_update_state_dicts(model_state_dict, ckpt_state_dict, c2_conversion=True):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 25. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 257-289, lines 292-333 into separate functions.

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/demo/visualizer.py
> +        if len(all_instances) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_original_unet.py
> +        return dq, dk, dv, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/engine/defaults.py
> +        if p is not none:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +        possible_matches = self.ids_lookup.get(token, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/dreambooth/utils/model_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 188.

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 02:28 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +                        raw_prompt = input()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/modules/ui_common.py
> +                sp.Popen(["xdg-open", path])
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 02:28 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/logger.py
> +    assert len(key) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on aws_extension/mme_utils.py
> +    os.system(f'./tools/s5cmd cp "{model_s3_pos}" ./')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if len(gt) == 0 and len(dt) ==0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 263 and 272.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if len(imgIds) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if len(gts) == 0 or len(dts) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/job/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/detection_utils.py
> +    if len(dataset_names) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/detection_checkpoint.py
> +        if len(queries) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/c2_model_loading.py
> +def convert_basic_c2_names(original_keys):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 26. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 37-63 into a separate function.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/modules/pix2pixhd.py
> +            blocks.append(ResnetBlock(**dilated_block_kwargs, dilation=2 ** (i + 1)))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;dilated_block_kwargs&#39; (index: 2 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;dilation_block_kind&#39;, &#39;dilated_blocks_n&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 05:50 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/resize_lora.py
> +          verbose_str+=f"{block_down_name:75} | "
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line numbers 258, 261, and 263.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/global_state.py
> +    if len(filter_by) != 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/keypoint_head.py
> +        if len(instances_per_image) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 77.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/modules/ui_gradio_extensions.py
> +        head += f'<script type="text/javascript" src="{webpath(script.path)}"></script>\n'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line number 28.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/modules/interrogate.py
> +                            res += f", ({match}:{score/100:.3f})"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line number 215.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/job/utils.py
> +    raise Exception(f'no content for file {s3_path}')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/yaml_handler.py
> +        kwargs.setdefault('Loader', Loader)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=os.path.dirname(__file__)).decode("ascii").strip()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/transforms/augmentation.py
> +                if default is attr:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_train_util.py
> +    return load_stable_diffusion_format, text_encoder1, text_encoder2, vae, unet, logit_scale, ckpt_info
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:50 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_xl.py
> +        elif weight is not None and len(round_brackets) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 112, 114, and 129.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +                        if len(local_models_check) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +        img = np.array(Image.open(d["file_name"]))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/lvis.py
> +            assert len(segm) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/rotated_coco_evaluation.py
> +            raise Exception("Unrecognized boxlist type")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 50.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/engine/hooks.py
> +        if len(get_bn_modules(model)) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +        return text_embeddings, text_pool, uncond_embeddings, uncond_pool, prompt_tokens
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 1139.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 05:52 UTC, NingLu commented on build_scripts/job/dreambooth/webhook.py
> +    attachment_id = hashlib.sha1(attachment_bytes).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/esrgan_model.py
> +        if len(model_paths) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/dataset.py
> +            except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Continue detected. https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/images.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 745.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/scripts.py
> +    global current_basedir
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 330.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco_panoptic.py
> +        img = np.array(Image.open(d["file_name"]))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 05:52 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return "", "", "", "", "", db_model_snapshots, msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 650.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/coco_evaluation.py
> +        if len(gt_boxes) == 0 or len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 516.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/backbone/resnet.py
> +            assert len(blocks) > 0, len(blocks)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/checkpoint_merger.py
> +                    checkpoint_path_1 = files[0] if len(files) > 0 else None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 210.

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/handlers/yaml_handler.py
> +        kwargs.setdefault('Dumper', Dumper)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `dict.setdefault()` method. We recommend using the `defaultdict` object to handle missing items in internal state because the default value is automatically generated when you access or modify a missing key. `defaultdict` can also be easier to use and understand.

[Learn more](https://docs.python.org/3/library/collections.html#collections.defaultdict)

2023-09-25 05:52 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f"tar xvf '{tar_name}'")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 05:52 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/openpose/util.py
> +    Ht, Wt = s
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;s&#39; (index: 1 | type: Unknown). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;x&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 05:54 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/file_client.py
> +            arg_key += f':{key}:{value}'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +    except Exception as e:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +                    value = eval(value, {})
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

If you do not have absolute control over the contents of the string passed to the `eval()` function, they might be maliciously used to execute an arbitrary function such as `__import__(&#39;os&#39;).system(&#34;rm -rf $HOME&#34;)`. If the string is expected to only contain literals, consider using the `ast.literal_eval()` method to safely evaluate strings containing Python values from untrusted sources.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-use-strings-to-call-functions-methods)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/modules/img2img.py
> +    return processed.images, generation_info_js, plaintext_to_html(processed.info), plaintext_to_html(processed.comments, classname="comments")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:54 UTC, NingLu commented on aws_extension/mme_utils.py
> +        os.system(f'./tools/s5cmd cp "{prefix_name}"* ./models/{model_type}/')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/get_data.py
> +        choice = input("\nPlease enter the number of the "
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The input method in Python 2 will read from standard input, evaluate and run the resulting string as python source code. This is similar, though in many ways worse, then using eval. On Python 2, use raw_input instead, input is safe in Python 3. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b322-input

2023-09-25 05:54 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +    date = datetime.datetime.utcfromtimestamp(seconds)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Naive datetime objects are treated by many datetime methods as local times, We recommend that you create aware timestamps with the `now` or `fromtimestamp` functions using the `tzinfo` to attribute to represent times in UTC. Do not use the [datetime.utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) because it returns only a `naive` datetime object. 

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +            ui_dict[f"db_{key}"] = value
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Modifying `object.__dict__` directly or writing to an instance of a class `__dict__` attribute directly is not recommended. Inside every module is a `__dict__` [object.dict](https://docs.python.org/3/stdtypes.html#object.dict) attribute which contains its symbol table. If you modify `object.__dict__`, then the symbol table is changed. Also, direct assignment to the `__dict__` attribute is not possible.

[Learn more](https://docs.python.org/3/library/stdtypes.html#object.__dict__)

Similar issue at line number 607.

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/backbone/swin.py
> +            return x, H, W, x_down, Wh, Ww
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 465.

2023-09-25 05:54 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train_network.py
> +        return sdxl_model_util.MODEL_VERSION_SDXL_BASE_V1_0, [text_encoder1, text_encoder2], vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_onnx.py
> +        elif weight is not None and len(round_brackets) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 136, 138, and 149.

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/modules/safe.py
> +                raise Exception(f"data.pkl not found in {filename}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 91.

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/layers/roi_align_rotated.py
> +        return grad_input, None, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/backbone/regnet.py
> +    return ws, ds, num_stages, total_stages, ws_all, ws_cont
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/models/mbv2_mlsd_large.py
> +        if len(inverted_residual_setting) == 0 or len(inverted_residual_setting[0]) != 4:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/meta_arch/fcos.py
> +        if len(reg_targets) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/torchscript_patch.py
> +    global _counter
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/image/io.py
> +    global imread_backend
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 58.

2023-09-25 05:54 UTC, NingLu commented on build_scripts/api/modules/hypernetworks/hypernetwork.py
> +    template_file = textual_inversion.textual_inversion_templates.get(template_filename, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 481.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/utils/events.py
> +        if len(stats) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 115.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +            ts_str = time.strftime("%Y%m%d%H%M%S", time.localtime())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use the `datetime` module for time zone conversions. The older `time` module doesn&#39;t work consistently with multiple time zones and shouldn&#39;t be used.

[Learn more](https://docs.python.org/3/library/time.html#module-time.)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/job/sd-scripts/train_textual_inversion.py
> +    def train(self, args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 90. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 353-364 into a separate function.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/engine/launch.py
> +    sock.bind(("", 0))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Binding a socket with an empty IP address causes the bound address to default to 0.0.0.0. This might bind a socket to all interfaces, which opens the socket to traffic from any IPv4 address and creates security risks.[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/ui_extra_networks_user_metadata.py
> +        if len(gallery) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +        item = self.data_labels.get(key)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using the `get` method without a default argument to return the value of a key in a dictionary. We recommended that you use a default argument so that if the value for your key is not found, a default value is returned. If a default value is not provided and the key is not found, then `None` is returned.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/merge_lora.py
> +                v2 = lora_metadata.get(train_util.SS_METADATA_KEY_V2, None)  # return string
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 128.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/job/helpers/log_parser.py
> +            return pd.DataFrame(loss_events), pd.DataFrame(lr_events), pd.DataFrame(ram_events), has_all
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +    if controlnet_state == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/job/dreambooth/webhook.py
> +    global hook_url
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/prompt_parser.py
> +    if len(res) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +    global hypernetworks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 801.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/pidinet/__init__.py
> +    global netNetwork
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/ros/midas_cpp/scripts/listener.py
> +        if self.show_output==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 42 and 43.

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/models/diffusion/uni_pc/uni_pc.py
> +        if len(t.shape) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/video/processing.py
> +    subprocess.call(cmd, shell=True)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are using a string to construct a shell command that invokes the shell explicitly via `shell=True`. This can be susceptible to shell injection [CWE 78](https://cwe.mitre.org/data/definitions/78.html). We recommend that you use `shlex.quote()` on Python 3.3+ and `pipes.quote()` on Python 3.2 and earlier to escape white space and shell meta-characters in strings that are used to construct shell commands.

[Learn more](https://docs.python.org/3/library/subprocess.html#security-considerations)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +                        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/modules/config_states.py
> +    creation_time = datetime.now().timestamp()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/api.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 05:57 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/carafe.py
> +        return grad_input, grad_masks, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/video/optflow.py
> +        raise Exception('Flow file header does not contain PIEH')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/datasets/pipelines/compose.py
> +            format_string += '\n'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line number 49.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/lvis_evaluation.py
> +        if len(gt_boxes) == 0 or len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 280.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/fileio/file_client.py
> +        value_buf = urlopen(filepath).read()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *urlopen*. The resource is allocated by call *request.urlopen*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close the object returned by *urlopen()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/optimizer/default_constructor.py
> +                if (prefix.find('conv_offset') != -1 and is_dcn_module
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you do not need the position returned by the [`find()`](https://docs.python.org/3/library/stdtypes.html#str.find) function. Consider using the operators [`in` and `not in`](https://docs.python.org/3/reference/expressions.html#membership-test-details) to check for simple membership, or more specific operations [`startswith()`](https://docs.python.org/3/library/stdtypes.html#str.startswith) and [`endswith()`](https://docs.python.org/3/library/stdtypes.html#str.endswith) to check for prefix and suffix relationships with the string.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/datasets/cityscapes.py
> +        if len(metrics) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/common.py
> +    global _DEFAULT_DATASET_FROM_LIST_SERIALIZE_METHOD
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/models/mbv2_mlsd_tiny.py
> +        if len(inverted_residual_setting) == 0 or len(inverted_residual_setting[0]) != 4:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/demo/visualizer.py
> +    def overlay_instances(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 38. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 785-843 into a separate function.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/roi_heads.py
> +        if len(proposals_per_image) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/img2img_inpainting.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 34 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_tensorrt_txt2img.py
> +        return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +            raise Exception('Please run accumulate() first')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/job/sd-scripts/library/slicing_vae.py
> +        assert _self.use_conv_transpose == False and _self.use_conv
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/modules/extra_networks.py
> +        extra_network = extra_network_registry.get(extra_network_name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 99.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/job/sd-scripts/library/attention_processors.py
> +        return dq, dk, dv, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 05:59 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora.py
> +    if down_lr_weight != None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 644 and 649.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_controlnet_reference.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 144 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 100-835 into a separate function.

2023-09-25 05:59 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/roi_heads/roi_heads.py
> +            has_gt = len(targets_per_image) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/evaluator.py
> +        stack.enter_context(torch.no_grad())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *no\_grad*. The resource is allocated by call *torch.no_grad*. Currently, there are execution paths that do not contain closure statements, for example, when *ExitStack.enter\_context()* throws an exception. To prevent this resource leak, close the object returned by *no\_grad()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion.py
> +        elif weight is not None and len(round_brackets) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 110, 112, and 123.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/detection_checkpoint.py
> +                data = pickle.load(f, encoding="latin1")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/proposal_generator/rpn.py
> +            if len(gt_boxes_i) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/parallel/scatter_gather.py
> +        if isinstance(obj, tuple) and len(obj) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 30 and 33.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/proposal_generator/proposal_utils.py
> +    if len(proposals) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco_panoptic.py
> +    assert len(sem_seg_file_to_entry) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/modules/sd_samplers.py
> +        raise Exception(f"Sampler {config.name} is not supported for SDXL")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/utils.py
> +    seed = dict(config).get('seed', None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/modules/ui.py
> +def create_ui():
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 162. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 1060-1562 into a separate function.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/resize_lora.py
> +    raise Exception("If using dynamic_method, then dynamic_param is required")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/job/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +            raise Exception('iouType not supported')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/job/sd-scripts/train_network.py
> +    def train(self, args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 112. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 229-244, lines 247-258 into separate functions.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 06:01 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/svd_merge_lora.py
> +    return merged_lora_sd, metadata, v2 == "True", base_model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/video_visualizer.py
> +    def draw_instance_predictions(self, frame, predictions):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 23. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 98-139 into a separate function.

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/nms.py
> +    nms_op = eval(nms_type)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

If you do not have absolute control over the contents of the string passed to the `eval()` function, they might be maliciously used to execute an arbitrary function such as `__import__(&#39;os&#39;).system(&#34;rm -rf $HOME&#34;)`. If the string is expected to only contain literals, consider using the `ast.literal_eval()` method to safely evaluate strings containing Python values from untrusted sources.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-use-strings-to-call-functions-methods)

2023-09-25 06:01 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/class_names.py
> +            labels = eval(alias2name[dataset] + '_classes()')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

If you do not have absolute control over the contents of the string passed to the `eval()` function, they might be maliciously used to execute an arbitrary function such as `__import__(&#39;os&#39;).system(&#34;rm -rf $HOME&#34;)`. If the string is expected to only contain literals, consider using the `ast.literal_eval()` method to safely evaluate strings containing Python values from untrusted sources.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-use-strings-to-call-functions-methods)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/modeling/backbone/mvit.py
> +    def __init__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 67 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 352-412 into a separate function.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/video_visualizer.py
> +        if len(ious) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/lvis.py
> +        img = np.array(Image.open(d["file_name"]))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 06:03 UTC, NingLu commented on build_scripts/job/sd-scripts/library/model_util.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/tf/utils.py
> +            raise Exception("Image dtype must be float32.")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 29.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/roi_align_rotated.py
> +        return grad_input, grad_rois, None, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +        assert(len(p.prompt) > 0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 760.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/visualizer.py
> +    def overlay_instances(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 37. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 688-745 into a separate function.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/deform_conv.py
> +        return grad_input, grad_offset, grad_weight, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/job/sd-scripts/train_db.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 67. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 127-138 into a separate function.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/job/sagemaker_entrypoint.py
> +                webui_status = pickle.load(webui_status_file)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Pickle and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b301-pickle

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/processor.py
> +    global model_canny
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 99, 109, 142, 156, 176, 187, 207, 273, 293, and 592.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +    file_type = subprocess.check_output(command, shell=True).decode('utf-8').strip()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +        if len(gt) == 0 and len(dt) ==0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/job/dreambooth/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +            return 'outside', min_dist, 0, 1
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 420.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +    def hook(self, model, sd_ldm, control_params, process):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 42 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 331-788 into a separate function.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/checkpoint/c2_model_loading.py
> +    for key_model in matched_model_keys:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line numbers 309, 312, 313, and 314.

2023-09-25 06:03 UTC, NingLu commented on build_scripts/job/sd-scripts/fine_tune.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 66. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 119-145, lines 148-159 into separate functions.

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_xl_reference.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 147 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 190-806 into a separate function.

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/pascal_voc_evaluation.py
> +        tree = ET.parse(f)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using xml.etree.ElementTree.parse to parse untrusted XML data is known to be vulnerable to XML attacks. Replace xml.etree.ElementTree.parse with its defusedxml equivalent function or make sure defusedxml.defuse_stdlib() is called https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b313-b320-xml-bad-elementtree

2023-09-25 06:06 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_fa.py
> +    conv_dim = kwargs.get("conv_dim", None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line numbers 442, 451, 456, 457, 458, 475, and 478.

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +        "date_created": str(datetime.datetime.now()),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +            'date': datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/comm.py
> +    global _LOCAL_PROCESS_GROUP
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/env.py
> +    global _ENV_SETUP_DONE
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/__init__.py
> +    except Exception as e:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +        existing = installed_extension_urls.get(normalize_git_url(url), None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/extras.py
> +    bake_in_vae_filename = sd_vae.vae_dict.get(bake_in_vae, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/cityscapes.py
> +        img = np.array(Image.open(PathManager.open(d["file_name"], "rb")))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/models/mbv2_mlsd_large.py
> +        return c1, c2, c3, c4, c5
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/models/diffusion/ddpm_edit.py
> +            return model_mean, posterior_variance, posterior_log_variance, logits
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 1079.

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/focal_loss.py
> +        return grad_input, None, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/sd_samplers_compvis.py
> +        return x, ts, cond, unconditional_conditioning
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/modules/sd_samplers.py
> +        config = all_samplers_map.get(name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/job/dreambooth/train_imagic.py
> +def train_imagic(args: DreamboothConfig):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 45 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 205-232, lines 235-343 into separate functions.

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/psa_mask.py
> +        return grad_input, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mlsd/utils.py
> +    return new_segments, squares, score_array, inter_points
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:06 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if len(imgIds) == len(catIds) == len(areaRng) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 142, 147, and 148.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/visualizer.py
> +        Popen(cmd, shell=True, stdout=PIPE, stderr=PIPE)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/gitpython_hack.py
> +        return (hexsha, typename, size, self.CatFileContentStream(size, bio))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/collect_env.py
> +    except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 155.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/hypernetworks/hypernetwork.py
> +    path = shared.hypernetworks.get(name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/hed/__init__.py
> +    global netNetwork
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_train_control_net_lllite_alt.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 68. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 149-165, lines 168-179 into separate functions.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora.py
> +    if (up_lr_weight != None and len(up_lr_weight) > max_len) or (down_lr_weight != None and len(down_lr_weight) > max_len):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line numbers 601, 605, 607, 610, 612, 618, and 624.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/uniformer/__init__.py
> +    global model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/preprocess.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Continue detected. https://bandit.readthedocs.io/en/latest/plugins/b112_try_except_continue.html

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/api/mme_utils.py
> +    os.system(f'./tools/s5cmd cp {model_s3_pos} ./')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 118, 119, 120, 122, and 125.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/sd_samplers_compvis.py
> +        return x, ts, cond, uncond, res
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/job/sd-scripts/train_textual_inversion.py
> +        return model_util.get_model_version_str_for_sd1_sd2(args.v2, args.v_parameterization), text_encoder, vae, unet
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/extras.py
> +    if len(info) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/processing.py
> +        latent_scale_mode = shared.latent_upscale_modes.get(self.hr_upscaler, None) if self.hr_upscaler is not None else shared.latent_upscale_modes.get(shared.latent_upscale_default_mode, "nearest")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/models/base_model.py
> +                if len(self.gpu_ids) > 0 and torch.cuda.is_available():
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/normalbae/models/submodules/decoder.py
> +            raise Exception('invalid architecture')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/autocrop.py
> +      for t in tries:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

Similar issue at line numbers 191 and 192.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if len(catNms) == len(supNms) == len(catIds) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 171, 172, and 173.

2023-09-25 06:08 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/global_state.py
> +    return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/cnn/bricks/generalized_attention.py
> +    def forward(self, x_input):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 106 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 369-401 into a separate function.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/openpose/body.py
> +                        if len(np.nonzero(membership == 2)[0]) == 0:  # merge
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/hypernetworks/hypernetwork.py
> +                        last_saved_image += f", prompt: {preview_text}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/data/masks.py
> +        str_hash = hashlib.sha1(arr).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 06:10 UTC, NingLu commented on build_scripts/job/sd-scripts/finetune/blip/med.py
> +            "encoder_hidden_states": model_kwargs.get("encoder_hidden_states", None),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 947.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return lora_model_name, 0, 0, [], msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 703 and 760.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/ui_extra_networks.py
> +                        subdir = subdir + "/"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                t=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f"),
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/utils.py
> +            raise Exception("Not a PFM file: " + path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 39.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/job/dreambooth/webhook.py
> +    attachment_id = hashlib.sha1(attachment_bytes).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                if enabled_units_len > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +    config = sd_samplers.all_samplers_map.get(name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/normalbae/models/submodules/efficientnet_repo/geffnet/activations/__init__.py
> +    global _OVERRIDE_FN
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 92.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/metrics.py
> +        pred_label = torch.from_numpy(np.load(pred_label))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *load*. The resource is allocated by call *numpy.load*. Currently, there are execution paths that do not contain closure statements, for example, when *torch.from\_numpy()* throws an exception. To prevent this resource leak, close the object returned by *load()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/utils.py
> +            raise Exception("Image dtype must be float32.")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 83.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/job/dreambooth/diff_to_sd.py
> +                    raise Exception("CORRUPTED MODEL: one of the q-k-v values for the text encoder was missing")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/job/sd-scripts/train_controlnet.py
> +def train(args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 59. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 260-265 into a separate function.

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/models/networks.py
> +    if len(gpu_ids) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +    with urllib.request.urlopen(url) as response:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-09-25 06:10 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/midas/blocks.py
> +        if self.bn==True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line number 280.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/utils/parrots_wrapper.py
> +    return _AdaptiveAvgPoolNd, _AdaptiveMaxPoolNd, _AvgPoolNd, _MaxPoolNd
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/modules/base.py
> +        raise Exception(f"Invalid deconv kind: {kind}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/midas/__init__.py
> +    global model
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/job/sd-scripts/bitsandbytes_windows/cextension.py
> +                raise Exception('CUDA SETUP: Setup Failed!')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/sd_unet.py
> +    global current_unet_option
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 36.

2023-09-25 06:12 UTC, NingLu commented on aws_extension/mme_utils.py
> +    os.system(f'./tools/s5cmd cp "{model_s3_pos}" ./')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 117, 118, 119, 121, and 124.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/ui.py
> +    if len(x) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/codeformer_model.py
> +        global codeformer
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                if reference_only and len(controlnet_images) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 865.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/extra_networks.py
> +        extra_network = extra_network_registry.get(extra_network_name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/localization.py
> +    fn = localizations.get(current_localization_name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion_xl.py
> +    if len(token_ids) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +                if len(self.mean_bank) > 0 and len(self.var_bank) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 732.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/dylora.py
> +    conv_dim = kwargs.get("conv_dim", None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line numbers 176 and 177.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/api.py
> +        if len(controlnet_input_images) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/job/modules/safe.py
> +                raise Exception(f"data.pkl not found in {filename}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.



Similar issue at line number 91.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/job/dreambooth/utils/utils.py
> +        raise Exception(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/transforms/augmentation_impl.py
> +                if len(overlaps) > 0 and overlaps.min() < min_iou:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 721.

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/uniformer/mmcv_custom/checkpoint.py
> +    if len(err_msg) > 0 and rank == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:12 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/ros/midas_cpp/scripts/talker.py
> +    if use_camera == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

Similar issue at line number 33.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +            request.urlretrieve(midas_urls[model_type], path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Audit url open for permitted schemes. Allowing use of file:/ or custom schemes is often unexpected. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b310-urllib-urlopen

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/coco.py
> +        if len(imgIds) == len(catIds) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 192.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +                        last_saved_image += f", prompt: {preview_text}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line number 639.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/registry.py
> +            if locate(candidate) is t:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `is` operator performs an identity comparison that uses the built-in `is()` method to test if the compared items are the same object or  not. It should be used with only singletons, such as `None`. We recommend that you use the `==` or `!=` equality operators to determine if two objects are equal.

[Learn more](https://docs.python.org/3/reference/datamodel.html#object.eq)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/midas/model_loader.py
> +    return model, transform, net_w, net_h
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +def create_model(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/hed/__init__.py
> +        return projection1, projection2, projection3, projection4, projection5
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/job/dreambooth/ui_functions.py
> +        return 100, 0, 0, 0, 0, "Please select a model."
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 95.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/runner/utils.py
> +    return time.strftime('%Y%m%d_%H%M%S', time.localtime())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use the `datetime` module for time zone conversions. The older `time` module doesn&#39;t work consistently with multiple time zones and shouldn&#39;t be used.

[Learn more](https://docs.python.org/3/library/time.html#module-time.)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/job/sd-scripts/finetune/tag_images_by_wd14_tagger.py
> +                        general_tag_text += ", " + tag_name
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

Similar issue at line number 159.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/modules/ui_settings.py
> +        raise Exception(f'bad options item type: {t} for key {key}')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/caffe2_modeling.py
> +        serialized_anchor_generator = io.BytesIO(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the following resource: *serialized\_anchor\_generator*. The resource is allocated by call *io.BytesIO*. Execution paths that do not contain closure statements were detected. To prevent this resource leak, close *serialized\_anchor\_generator* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 06:14 UTC, NingLu commented on build_scripts/job/dreambooth/dataclasses/db_config.py
> +    if isinstance(model_name, list) and len(model_name) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/coco.py
> +            if "bbox" in obj and len(obj["bbox"]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 189.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/torchscript_patch.py
> +        cls.__annotations__["training"] = torch.jit.Final[bool]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It seems that you used an arbitrary value while setting the type using `__annotations__`. This value is evaluated when `typing.get_type_hints` is invoked to receive annotations, which can lead to invocation of arbitrary code. We recommend that you set the type statically, or set type dynamically only if you trust the type.

[Learn more](https://cwe.mitre.org/data/definitions/95.html)

Similar issue at line number 406.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/ball_query.py
> +        return None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/stable_diffusion_tensorrt_img2img.py
> +        return (
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/models/backbones/resnet.py
> +    def __init__(self,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 63 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 154-206, lines 209-217 into separate functions.

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/lama/saicinpainting/training/data/masks.py
> +        str_hash = hashlib.sha1(arr).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 06:14 UTC, NingLu commented on build_scripts/api/modules/modelloader.py
> +        commandline_model_path = commandline_options.get(cmd_name, None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/deform_roi_pool.py
> +        return grad_input, None, grad_offset, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/openpose/cv_ox_pose.py
> +    if len(out_bbox) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +def train_embedding(id_task, embedding_name, learn_rate, batch_size, gradient_step, data_root, log_directory, training_width, training_height, varsize, steps, clip_grad_mode, clip_grad_value, shuffle
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 165 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 455-466 into a separate function.

2023-09-25 06:17 UTC, NingLu commented on build_scripts/job/sd-scripts/library/original_unet.py
> +        return dq, dk, dv, None, None, None, None
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/evaluation/coco_evaluation.py
> +            raise Exception("Please run accumulate() first")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 06:17 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +            if noise == None:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/utils/env.py
> +            + int(datetime.now().strftime("%S%f"))
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/hook.py
> +    p = kwargs.get('p', None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/job/sd-scripts/sdxl_gen_img.py
> +            ts_str = time.strftime("%Y%m%d%H%M%S", time.localtime())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use the `datetime` module for time zone conversions. The older `time` module doesn&#39;t work consistently with multiple time zones and shouldn&#39;t be used.

[Learn more](https://docs.python.org/3/library/time.html#module-time.)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/ui_extensions.py
> +    global available_extensions
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/img2img.py
> +                if len(masks_found) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +        assert(len(p.prompt) > 0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 985.

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +                self.init_img_hash = hashlib.md5(img.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/data/datasets/register_cityscapes_panoptic.py
> +        image_file = image_dict.get(ann["image_id"], None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/hypernetworks/hypernetwork.py
> +        self.dropout_structure = kwargs.get('dropout_structure', None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/models/diffusion/uni_pc/uni_pc.py
> +        if len(D1s) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line numbers 589 and 610.

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmcv/ops/assign_score_withk.py
> +        return grad_scores, grad_point_features, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +                except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/export/shared.py
> +        inputs_status = [_known_status.get(b, None) for b in versioned_inputs]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line number 425.

2023-09-25 06:17 UTC, NingLu commented on build_scripts/api/modules/sd_models.py
> +except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:00 UTC, NingLu commented on build_scripts/job/sd-scripts/library/train_util.py
> +        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=os.path.dirname(__file__)).decode("ascii").strip()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/config/lazy.py
> +                module.__dict__[name] = val
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Modifying `object.__dict__` directly or writing to an instance of a class `__dict__` attribute directly is not recommended. Inside every module is a `__dict__` [object.dict](https://docs.python.org/3/stdtypes.html#object.dict) attribute which contains its symbol table. If you modify `object.__dict__`, then the symbol table is changed. Also, direct assignment to the `__dict__` attribute is not possible.

[Learn more](https://docs.python.org/3/library/stdtypes.html#object.__dict__)

2023-09-25 08:00 UTC, NingLu commented on build_scripts/job/sd-scripts/library/sdxl_lpw_stable_diffusion.py
> +        return text_embeddings, text_pool, uncond_embeddings, uncond_pool
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 426.

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/modules/face_restoration.py
> +    if len(face_restorers) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:00 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora.py
> +    conv_dim = kwargs.get("conv_dim", None)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are using the `get()` method to retrieve the value for a key from a dictionary. If the key is not present, then `get()` returns the value that is passed in its optional second parameter. If if the key is not present, then `None` is the default return value. Therefore, there is no need to explicitly specify `None` in the second parameter.

[Learn more](https://docs.python.org/3/library/stdtypes.html#dict.get)

Similar issue at line numbers 422, 431, 436, 437, 438, 455, and 458.

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/modules/custome_pipeline/lpw_stable_diffusion.py
> +            if len(weights[i]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/modules/textual_inversion/textual_inversion.py
> +            raise Exception(f"Couldn't identify {filename} as neither textual inversion embedding nor diffuser concept.")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/html.py
> +        f = open(html_file, 'wt')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *f*. The resource is allocated by call *builtins.open*. The resource is referenced at lines 72, 73. The resource is closed at line 73. There are other execution paths that do not contain closure statements, for example, when *doc.render()* throws an exception. To prevent this resource leak, close *f* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/pycocotools/cocoeval.py
> +                        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/leres/pix2pix/util/get_data.py
> +        r = requests.get(self.url)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

We detected a URL in your code that uses an unencrypted HTTP protocol connection. This might expose sensitive data to third parties. To prevent this, we recommend that you construct all URLs using the secure HTTPS protocol.

[Learn more](https://docs.python-requests.org/en/master/user/quickstart/#make-a-request)

2023-09-25 08:00 UTC, NingLu commented on build_scripts/api/modules/sd_samplers.py
> +    global samplers, samplers_for_img2img
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +                    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +        if len(gt_boxes) == 0 or len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 517.

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/helpers/version_helper.py
> +    current_branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=shared.extension_path,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +def performance_wizard(model_name):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 75 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 227-294 into a separate function.

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +    if len(args) > 0 and isinstance(args[0], torch.Tensor) and args[0].device.type == 'mps':
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/train_imagic.py
> +            input_image = Image.open(check).convert("RGB")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *tokenizer()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +    model_base = osp.join(working_dir, model_name) if model_name else working_dir
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem:**
 This line of code lacks validation when processing input data through the following parameter: &#39;working_dir&#39; (index: 0 | type: str). The parameter is exposed to external callers, because its enclosing class and method are publicly accessible. This means that upstream validation, if it exists, can be bypassed. Other validated parameters: &#39;model_name&#39;, &#39;file_extra&#39;. Malicious, malformed, or unbounded inputs can cause unexpected runtime behavior or crashes, and can slow performance.

**Fix:**
 Add checks to ensure the validity of the parameter&#39;s value, such as testing it for nullness, emptiness, or equality. Or to prevent direct calls to it, [reduce the method&#39;s visibility](https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles) using single or double underscore.

 Learn more about potential threats and guidance from the [Common Weakness Enumeration website](https://cwe.mitre.org/data/definitions/693.html) and the [OWASP Cheat Sheet series](https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html).

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        return "", "", "", "", "", db_model_snapshots, msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 650.

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/utils/gen_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 378.

2023-09-25 08:31 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +        raise Exception(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +                    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +            prompt += f"{i}: {p}\r\n"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +    attachment_id = hashlib.sha1(attachment_bytes).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        except Exception:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/helpers/version_helper.py
> +        commit_history = subprocess.run(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Passing user-provided input to Python subprocess, OS, and command functions without validation or sanitization makes your code vulnerable to running arbitrary OS commands. To prevent this, implement input validation and use secure functions. For more information, see [CWE-77](https://cwe.mitre.org/data/definitions/77.html), [CWE-78](https://cwe.mitre.org/data/definitions/78.html) and [CWE-88](https://cwe.mitre.org/data/definitions/88.html)

Similar issue at line number 471.

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +            ui_dict[f"db_{key}"] = value
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Modifying `object.__dict__` directly or writing to an instance of a class `__dict__` attribute directly is not recommended. Inside every module is a `__dict__` [object.dict](https://docs.python.org/3/stdtypes.html#object.dict) attribute which contains its symbol table. If you modify `object.__dict__`, then the symbol table is changed. Also, direct assignment to the `__dict__` attribute is not possible.

[Learn more](https://docs.python.org/3/library/stdtypes.html#object.__dict__)

Similar issue at line number 607.

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +            [k if k == v else f'{k}: {f"{v}" if "," in str(v) else v}' for k, v in generation_params.items()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Comprehensions for `list`, `dict`, and `set` with more than two control subexpressions can be difficult to understand so should be avoided. The following is an example of using a comprehension with four control statements: `[y.upper() for x in text if len(x) == 3 for y in x if y.startswith(&#39;f&#39;)]`. 

[Learn more](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions)

2023-09-25 08:33 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/utils/gen_utils.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    grid = Image.new('RGB', size=(cols * w, rows * h), color='black')
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *grid*. The resource is allocated by call *Image.new*. The resource is referenced at line 536. The resource is returned at line 538. There are other execution paths that don&#39;t close the resource or return it, for example, when *hasNext()* throws an exception. To prevent this resource leak, close *grid* along these other paths before you exit this method.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +def create_model(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +            ((len(args) > 0 and isinstance(args[0], torch.device) and args[0].type == 'mps') or
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/train_imagic.py
> +def train_imagic(args: DreamboothConfig):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 45 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code blocks on lines 205-232, lines 235-343 into separate functions.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/dataclasses/db_config.py
> +            raise Exception(f"shared_diffusers_path is \"{self.shared_diffusers_path}\" but use_lora is false")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        return lora_model_name, 0, 0, [], msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 703 and 760.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +def compile_checkpoint(model_name: str, lora_file_name: str = None, reload_models: bool = True, log: bool = True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 114 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    if isinstance(model_name, list) and len(model_name) > 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        return "", "", "", 0, 0, "", "", "", "", res, "", err_msg
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line numbers 977, 992, and 1005.

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:35 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 415, 467, 471, and 473.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +                if len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line numbers 129, 135, 141, 147, and 153.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/helpers/version_helper.py
> +    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +                    raise Exception("CORRUPTED MODEL: one of the q-k-v values for the text encoder was missing")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Using `Exception` and `BaseException` can make your code prone to errors and difficult to maintain. Instead, we recommend using one of the [Built-in Exceptions](https://docs.python.org/3/library/exceptions.html) or creating a custom exception class that is derived from `Exception` or one of its subclasses.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image = rotate_image_straight(image)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *image*. The resource is allocated by call *image_utils.rotate_image_straight*. The resource is referenced at lines 451, 454, 456, 457, 458, 459, 460, 463, 465, 466, 469, 470, 471, 473, 476, 479. The resource is returned at line 477. There are other execution paths that don&#39;t close the resource or return it, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close *image* along these other paths before you exit this method.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        return 100, 0, 0, 0, 0, "Please select a model."
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

Similar issue at line number 95.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +        self.re_word = re.compile(shared.dataset_filename_word_regex) if len(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    with open(config_file, 'r') as openfile:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

You are using potentially untrusted inputs to access a file path. To protect your code from a path traversal attack, verify that your inputs are sanitized. Learn more about path traversal vulnerabilities on the [Common Weakness Enumeration](https://cwe.mitre.org/data/definitions/22.html) website and the [Open Web Application Security Project](https://owasp.org/www-community/attacks/Path_Traversal) website.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/helpers/version_helper.py
> +    current_branch = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=shared.extension_path,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +    date = datetime.datetime.utcfromtimestamp(seconds)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Naive datetime objects are treated by many datetime methods as local times, We recommend that you create aware timestamps with the `now` or `fromtimestamp` functions using the `tzinfo` to attribute to represent times in UTC. Do not use the [datetime.utcnow()](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) because it returns only a `naive` datetime object. 

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +stdout: {result.stdout.decode(encoding="utf8", errors="ignore") if len(result.stdout) > 0 else '<empty>'}
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 123.

2023-09-25 08:37 UTC, NingLu commented on build_scripts/api/dreambooth/sd_to_diff.py
> +        original_config_file = get_config_file(train_unfrozen, v2=is_512 == False, prediction_type=prediction_type)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image = Image.open(image_path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *image*. The resource is allocated by call *Image.open*. The resource is referenced at lines 451, 454, 456, 457, 458, 459, 460, 463, 465, 466, 469, 470, 471, 473, 476, 479. The resource is returned at line 477. There are other execution paths that don&#39;t close the resource or return it, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close *image* along these other paths before you exit this method.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/instance_evaluation.py
> +                if len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +    global hook_url
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/text_utils.py
> +def build_strict_tokens(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 997.

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +    global models_path, script_path, ckpt_dir, device_id, disable_safe_unpickle, dataset_filename_word_regex, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 52 and 318.

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/utils/gen_utils.py
> +def generate_classifiers(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 93 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/sd_to_diff.py
> +def extract_checkpoint(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 69 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 145-219 into a separate function.

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +        out_imgs = [Image.open(img) if isinstance(img, str) else img for img in imgs]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *append()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +            return pd.DataFrame(loss_events), pd.DataFrame(lr_events), pd.DataFrame(ram_events), has_all
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        if len(y) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:38 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_tgt_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/utils/text_utils.py
> +def build_strict_tokens(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Possible hardcoded password: &#39;&#39; https://bandit.readthedocs.io/en/latest/plugins/b107_hardcoded_password_default.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +    attachment_id = hashlib.sha1(attachment_bytes).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/instance_evaluation.py
> +                if len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        self.job_timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_tgt_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 997.

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +        if len(y) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image = Image.open(image_path)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code contains a resource that might not be closed properly. This can cause a resource leak that slows down or crashes your system.

**Fix**
Consider closing the following resource: *image*. The resource is allocated by call *Image.open*. The resource is referenced at lines 451, 454, 456, 457, 458, 459, 460, 463, 465, 466, 469, 470, 471, 473, 476, 479. The resource is returned at line 477. There are other execution paths that don&#39;t close the resource or return it, for example, when *numpy.array()* throws an exception. To prevent this resource leak, close *image* along these other paths before you exit this method.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +    assert len(coco_results) > 0
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +        result = subprocess.run(command, shell=True, env=os.environ if custom_env is None else custom_env)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call with shell=True identified, security issue. https://bandit.readthedocs.io/en/latest/plugins/b602_subprocess_popen_with_shell_equals_true.html

2023-09-25 08:39 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        msg += f"<br>{key}: {log_dict[key]}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 08:40 UTC, NingLu commented on build_scripts/api/dreambooth/ui_functions.py
> +        msg += f"<br>{key}: {log_dict[key]}"
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are concatenating a string inside a loop. Concatenating immutable sequences will always results in a new object. This means that building up a sequence by repeated concatenation will have a quadratic runtime cost in the total sequence length. For efficiency and to get a linear runtime cost, consider appending values to a list and concatenating that list using [str.join()](https://docs.python.org/3/library/stdtypes.html#str.join) or [bytes.join()](https://docs.python.org/3/library/stdtypes.html#bytes.join) method.

[Learn more](https://docs.python.org/3/faq/programming.html#what-is-the-most-efficient-way-to-concatenate-many-strings-together)

2023-09-25 08:40 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +    attachment_id = hashlib.sha1(attachment_bytes).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Use of insecure MD2, MD4, MD5, or SHA1 hash function. https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

2023-09-25 08:40 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 188.

2023-09-25 08:40 UTC, NingLu commented on build_scripts/api/dreambooth/diff_to_sd.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell: Seems safe, but may be changed in the future, consider rewriting without shell https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +            if len(s[s > -1]) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/shared.py
> +    global models_path, script_path, ckpt_dir, device_id, disable_safe_unpickle, dataset_filename_word_regex, \
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line numbers 52 and 318.

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

Similar issue at line number 188.

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/gen_utils.py
> +def generate_classifiers(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 93 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/oneformer/evaluation/detection_coco_evaluator.py
> +        if len(predictions) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +        out_imgs = [Image.open(img) if isinstance(img, str) else img for img in imgs]
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

**Problem**
This line of code might contain a resource leak. Resource leaks can cause your system to slow down or crash.

**Fix**
Consider closing the resource returned by the following method call: *open*. The resource is allocated by call *Image.open*. Currently, there are execution paths that do not contain closure statements, for example, when *append()* throws an exception. To prevent this resource leak, close the object returned by *open()* in a try-finally block or declare it using a `with` statement.

**More info**
[View details about the `with` statement in the Python developer&#39;s guide](https://www.python.org/dev/peps/pep-0343/) (external link).

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    image_base = hashlib.sha1(image.tobytes()).hexdigest()
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The hashing algorithm you are using is unsecure and might lead to cryptographic vulnerabilities. [Learn more](https://en.wikipedia.org/wiki/Hash_function_security_summary). Use a more secure hashing algorithm when creating message digests using hashlib. For example, use SHA224, SHA256, SHA384, or SHA512. 

[Learn more](https://docs.python.org/3/library/hashlib.html#hash-algorithms)

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/gen_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/helpers/log_parser.py
> +            return pd.DataFrame(loss_events), pd.DataFrame(lr_events), pd.DataFrame(ram_events), has_all
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears you are unpacking more than three variables while using a function that returns more than one variable. Using a large number of return values is prone to errors. We recommend that you return a small class or `namedtuple` instance instead.

[Learn more](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a partial executable path https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Starting a process with a shell, possible injection detected, security issue. https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/webhook.py
> +    global hook_url
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/utils/model_utils.py
> +        except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:41 UTC, NingLu commented on build_scripts/api/dreambooth/train_dreambooth.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:43 UTC, NingLu commented on build_scripts/api/helpers/version_helper.py
> +    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=shared.extension_path, capture_output=True,
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

subprocess call - check for execution of untrusted input. https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

2023-09-25 08:43 UTC, NingLu commented on build_scripts/api/dreambooth/utils/image_utils.py
> +    except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:43 UTC, NingLu commented on build_scripts/api/dreambooth/sd_to_diff.py
> +def extract_checkpoint(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 69 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 145-219 into a separate function.

2023-09-25 08:43 UTC, NingLu commented on build_scripts/api/dreambooth/secret.py
> +except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Try, Except, Pass detected. https://bandit.readthedocs.io/en/latest/plugins/b110_try_except_pass.html

2023-09-25 08:43 UTC, NingLu commented on build_scripts/api/helpers/image_builder.py
> +            except:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you are generically passing an `Exception` object without performing any other operation on it. This may hide error conditions that can otherwise be quickly detected and addressed. We recommend that you catch a more specific exception. If the code must broadly catch all exceptions, consider logging the stack trace using the [logging.exception()](https://docs.python.org/3/library/logging.html#logging.exception) API. For example,

```
try:
    x = 1 / 0
except ZeroDivisionError as e:
    logging.exception(&#39;ZeroDivisionError: %s&#39;, e)

```

2023-10-07 04:39 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 500, 552, 556, and 558.

2023-10-07 04:39 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Passing user-provided input to Python subprocess, OS, and command functions without validation or sanitization makes your code vulnerable to running arbitrary OS commands. To prevent this, implement input validation and use secure functions. For more information, see [CWE-77](https://cwe.mitre.org/data/definitions/77.html), [CWE-78](https://cwe.mitre.org/data/definitions/78.html) and [CWE-88](https://cwe.mitre.org/data/definitions/88.html)

Similar issue at line number 556.

2023-10-07 04:39 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +    def __init__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 166 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 161-284 into a separate function.

2023-10-08 09:43 UTC, alvindaiyan requested changes
there are c files as well, make sure the pr is clean

2023-10-20 03:13 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +        print(f"Writing new secret {secret} to {secret_file}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/environment.yaml
> +    - opencv-python==4.6.0.66
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears your code contains a hardcoded static IP address. This practice significantly increases the risk of security breaches. Anyone aware of this IP can potentially launch targeted attacks on your network, resulting in unauthorized access to your data and misuse of your resources. Possible remediation approaches are:
	 1. Manage IP addresses using environment variables:
		 a) Identify the static IP address and store it in an environment variable on your local and production server.
		 b) Replace the hardcoded IP address in your code with references to environment variables.
	 2. Use Domain Name System (DNS) for addressing:
		 a) Rather than hardcoding IP addresses, use DNS names that can be mapped to various IP addresses as needed.
		 b) This allows for greater flexibility and resilience in case of changes to your network infrastructure.
	 3. Implement proper access control and security measures:
		 a) Ensure that your network firewall rules are up to date and properly configured to prevent unauthorized access.
		 b) Regularly audit your network logs to identify any unusual activity or access attempts from unknown IPs.

 To learn more about securely managing IP addresses and best practices, please consult appropriate networking and network security resources.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/dreambooth/secret.py
> +        print(f"Writing new secret {secret} to {secret_file}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 512, 564, 568, and 570.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/zoe/zoedepth/models/base_models/midas_repo/README.md
> +* [Jul 2020] Added TensorFlow and ONNX code. Added [online demo](http://35.202.76.57/).
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears your code contains a hardcoded static IP address. This practice significantly increases the risk of security breaches. Anyone aware of this IP can potentially launch targeted attacks on your network, resulting in unauthorized access to your data and misuse of your resources. Possible remediation approaches are:
	 1. Manage IP addresses using environment variables:
		 a) Identify the static IP address and store it in an environment variable on your local and production server.
		 b) Replace the hardcoded IP address in your code with references to environment variables.
	 2. Use Domain Name System (DNS) for addressing:
		 a) Rather than hardcoding IP addresses, use DNS names that can be mapped to various IP addresses as needed.
		 b) This allows for greater flexibility and resilience in case of changes to your network infrastructure.
	 3. Implement proper access control and security measures:
		 a) Ensure that your network firewall rules are up to date and properly configured to prevent unauthorized access.
		 b) Regularly audit your network logs to identify any unusual activity or access attempts from unknown IPs.

 To learn more about securely managing IP addresses and best practices, please consult appropriate networking and network security resources.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/modules/pipeline_utils.py
> +    if controlnet_state == True:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The `==` and `!=` operators use the compared objects&#39; ` __eq__` method to test if they are equal. To check if an object is a singleton, such as `None`, we recommend that you use the `is` identity comparison operator.

[Learn more](https://docs.python.org/3/reference/expressions.html#is)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/dreambooth/secret.py
> +        print(f"Deleting secrets file: {secret_file}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/lvis_v0_5_categories.py
> +LVIS_CATEGORIES = [{'frequency': 'r', 'id': 1, 'synset': 'acorn.n.01', 'synonyms': ['acorn'], 'def': 'nut from an oak tree', 'name': 'acorn'}, {'frequency': 'c', 'id': 2, 'synset': 'aerosol.n.02', 's
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Usage of unprofessional language detected - flaps, jesus, knob, ginger, cow, cock, beaver.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/job/sd-scripts/requirements.txt
> +opencv-python==4.7.0.68
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears your code contains a hardcoded static IP address. This practice significantly increases the risk of security breaches. Anyone aware of this IP can potentially launch targeted attacks on your network, resulting in unauthorized access to your data and misuse of your resources. Possible remediation approaches are:
	 1. Manage IP addresses using environment variables:
		 a) Identify the static IP address and store it in an environment variable on your local and production server.
		 b) Replace the hardcoded IP address in your code with references to environment variables.
	 2. Use Domain Name System (DNS) for addressing:
		 a) Rather than hardcoding IP addresses, use DNS names that can be mapped to various IP addresses as needed.
		 b) This allows for greater flexibility and resilience in case of changes to your network infrastructure.
	 3. Implement proper access control and security measures:
		 a) Ensure that your network firewall rules are up to date and properly configured to prevent unauthorized access.
		 b) Regularly audit your network logs to identify any unusual activity or access attempts from unknown IPs.

 To learn more about securely managing IP addresses and best practices, please consult appropriate networking and network security resources.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/modules/ngrok.py
> +        print(f'Invalid ngrok authtoken? ngrok connection aborted due to: {e}\n'
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Passing user-provided input to Python subprocess, OS, and command functions without validation or sanitization makes your code vulnerable to running arbitrary OS commands. To prevent this, implement input validation and use secure functions. For more information, see [CWE-77](https://cwe.mitre.org/data/definitions/77.html), [CWE-78](https://cwe.mitre.org/data/definitions/78.html) and [CWE-88](https://cwe.mitre.org/data/definitions/88.html)

Similar issue at line number 568.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/pascal_voc.py
> +    "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person",
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Usage of unprofessional language detected - cow.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/mmpkg/mmseg/core/evaluation/class_names.py
> +        'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse',
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Usage of unprofessional language detected - cow.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/lvis_v1_categories.py
> +LVIS_CATEGORIES = [{'frequency': 'c', 'synset': 'aerosol.n.02', 'synonyms': ['aerosol_can', 'spray_can'], 'id': 1, 'def': 'a dispenser that holds a substance under pressure', 'name': 'aerosol_can'},
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Usage of unprofessional language detected - jesus, knob, ginger, cow, cock, beaver.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/job/lora_diffusion/lora.py
> +        print(token)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

Similar issue at line numbers 881, 883, 887, and 888.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/annotator/oneformer/detectron2/data/datasets/builtin_meta.py
> +    {"color": [120, 166, 157], "isthing": 1, "id": 21, "name": "cow"},
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Usage of unprofessional language detected - cow.

2023-10-20 03:13 UTC, NingLu commented on build_scripts/job/sd-scripts/networks/lora_interrogator.py
> +    print(f"[{i:3d}]: {token:5d} {string:<20s}: {diff:.5f}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-20 03:13 UTC, NingLu commented on build_scripts/job/dreambooth/secret.py
> +        print(f"Deleting secrets file: {secret_file}")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

It appears that you have passed parameters to the `print` method that can expose sensitive information in console. This can compromise user privacy and is often illegal.

[Learn more](https://cwe.mitre.org/data/definitions/200.html)

2023-10-31 03:16 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +    def __init__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function contains 166 lines of code, not including blank lines or lines with only comments, Python punctuation characters, identifiers, or literals. By comparison, 99% of the functions in the CodeGuru reference dataset contain fewer lines of code. Large functions might be difficult to read and have logic that is hard to understand and test.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 153-276 into a separate function.

2023-10-31 03:16 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +    global hypernetworks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 817.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/job/sd-scripts/gen_img_diffusers.py
> +    def __call__(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The cyclomatic complexity of this function is 82. By comparison, 99% of the functions in the CodeGuru reference dataset have a lower cyclomatic complexity. This indicates the function has a high number of decisions and it can make the logic difficult to understand and test. We recommend that you simplify this function or break it into multiple functions.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/api/extensions/sd-aws-ext/scripts/controlnet.py
> +    def process(self, p, *args):
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This function calls 39 other functions. By comparison, 99% of the functions in the CodeGuru reference dataset use fewer. This indicates the function is highly coupled with other functions. A function that is highly coupled with other functions is difficult to understand and its behavior might change unexpectedly when one of its referenced functions is updated. High coupling could also increase the integration test complexity, maintenance cost and technical debt.

We recommend that you simplify this function or break it into multiple functions. For example, consider extracting the code block on lines 679-686 into a separate function.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/api/modules/shared.py
> +    global hypernetworks
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Global variables are dangerous because they can be simultaneously accessed from multiple sections of a program. This frequently results in bugs. Most bugs involving global variables arise from one function reading and acting on the value of a global variable before another function has the chance to set it to an appropriate value. We recommend using a configuration module to mutate global state.

[Learn more](https://docs.python.org/3/faq/programming.html#how-do-i-share-global-variables-across-modules)

Similar issue at line number 798.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +        assert(len(p.prompt) > 0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 784.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/api/modules/pipeline_utils.py
> +                if reference_only and len(controlnet_images) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 67.

2023-11-03 03:45 UTC, NingLu commented on build_scripts/job/dreambooth/utils/image_utils.py
> +        self.re_word = re.compile(shared.dataset_filename_word_regex) if len(
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-11-03 08:13 UTC, NingLu commented on build_scripts/api/modules/pipeline.py
> +        assert(len(p.prompt) > 0)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

Similar issue at line number 780.

2023-11-06 04:13 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                        os.system("df -h")
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

This line of code makes an outdated API call to start and communicate with processes. We recommend that you use the `subprocess` module to start new processes, connect with their pipes, and get their return codes.

[Learn more](https://docs.python.org/3/library/subprocess.html)

Similar issue at line numbers 505, 557, 561, and 563.

2023-11-06 04:13 UTC, NingLu commented on build_scripts/api/modules/api/api.py
> +                    os.system(delete_src_command)
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

Passing user-provided input to Python subprocess, OS, and command functions without validation or sanitization makes your code vulnerable to running arbitrary OS commands. To prevent this, implement input validation and use secure functions. For more information, see [CWE-77](https://cwe.mitre.org/data/definitions/77.html), [CWE-78](https://cwe.mitre.org/data/definitions/78.html) and [CWE-88](https://cwe.mitre.org/data/definitions/88.html)

Similar issue at line number 561.

2023-11-07 07:48 UTC, alvindaiyan commented
will recommit

2023-11-07 07:48 UTC, closed without merging