feat: Improved endpoint design
awslabs/stable-diffusion-aws-extension pull request #246
Opened 2023-10-26 02:01 UTC by elonniu

## Description

- Using Lambda Runtime instead of Docker Image.
- Fixed Endpoint status loss or out of sync issues.
- Decouple message notifications using EventBridge.
- Use `aws_lambda_powertools`.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-10-26 02:05 UTC, NingLu commented on middleware_api/lambda/inference/app.py
> +        current_time = str(datetime.now())
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

The naive datetime objects are treated by many datetime methods as local times, it is preferred to use aware datetimes to represent times in UTC. The recommended way to create an aware datetime object representing a specific timestamp in UTC is by passing `tzinfo` as an argument to the method.

[Learn more](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)

Similar issue at line number 428.

2023-10-26 02:05 UTC, NingLu commented on middleware_api/lambda/inference_v2/sagemaker_endpoint_events.py
> +        if len(record_list) == 0:
Recommendation generated by Amazon CodeGuru Reviewer. Leave feedback on this recommendation by replying to the comment or by reacting to the comment using emoji.

To check if a container or sequence (string, list, tuple) is empty, use `if not val`. Do not compare its length using `if len(val) == 0`

[Learn more](https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq)

2023-10-27 06:39 UTC, alvindaiyan requested changes
overall, this is awesome changes

2023-10-27 06:39 UTC, alvindaiyan commented on infrastructure/src/sd-inference/sagemaker-endpoints-event.ts
> +                            prefix: 'infer-endpoint-'
does we defined this prefix?

2023-10-29 14:27 UTC, elonniu commented on infrastructure/src/sd-inference/sagemaker-endpoints-event.ts
> +                            prefix: 'infer-endpoint-'
yes

2023-10-30 09:09 UTC, alvindaiyan approved these changes
gooooooooo

2023-10-30 09:12 UTC, merged